//! The [`CommitDelta`] captures everything that changed in a single committed
//! transaction. It is the unit of replication: the Primary publishes deltas to
//! a distributed log, and Replicas consume them to update their local state.
//!
//! This module also defines the [`DistributedLog`] trait — the abstraction over
//! whatever transport carries deltas between nodes.

use std::{
    collections::{
        BTreeMap,
        BTreeSet,
    },
    sync::Arc,
};

use async_trait::async_trait;
use common::{
    document::DocumentUpdate,
    persistence::{
        DocumentLogEntry,
        PersistenceIndexEntry,
    },
    types::Timestamp,
};
use futures::stream::BoxStream;
use value::{
    TableName,
    TabletId,
};

use crate::{
    partition::PartitionId,
    write_log::WriteSource,
};

/// Everything that changed in a single committed transaction.
///
/// Produced by the Committer after a successful commit. Contains enough
/// information for a Replica to:
/// 1. Update its [`SnapshotManager`] (via document_updates)
/// 2. Append to its local [`WriteLog`] (for subscription invalidation)
/// 3. Maintain ordering (via the commit timestamp)
#[derive(Clone, Debug)]
pub struct CommitDelta {
    /// The commit timestamp assigned by the source partition's Committer.
    ///
    /// Receivers may translate this into a later local apply timestamp for
    /// their own MVCC/write-log state, but this value remains the origin
    /// timestamp used for source-partition watermarks and redelivery dedup.
    pub ts: Timestamp,

    /// Document writes for persistence replay. Contains document ID, new value,
    /// and previous timestamp.
    pub document_writes: Arc<Vec<DocumentLogEntry>>,

    /// Document updates for snapshot replication. Contains old and new document
    /// values, which the Replica needs to update its SnapshotManager
    /// (table registry, index registry, schemas, etc.).
    pub document_updates: Vec<DocumentUpdate>,

    /// Index updates generated by this commit.
    pub index_writes: Arc<Vec<PersistenceIndexEntry>>,

    /// The source of the write (e.g. which mutation function triggered it).
    pub write_source: WriteSource,

    /// Total bytes written to persistence.
    pub write_bytes: u64,

    /// Mapping from the Primary's TabletIds to table names.
    /// Replicas use this to remap document IDs to their own local TabletIds
    /// since each database instance generates unique TabletIds.
    pub tablet_id_to_table_name: BTreeMap<TabletId, TableName>,

    /// Partition that originated this replicated event.
    ///
    /// Used to advance per-partition freshness frontiers on replicas, so
    /// remote reads can prove they were validated against a sufficiently
    /// up-to-date replica state.
    pub source_partition: Option<PartitionId>,
}

#[async_trait]
pub trait ReplicationAck: Send + 'static {
    async fn ack(self: Box<Self>) -> anyhow::Result<()>;

    async fn nak(self: Box<Self>) -> anyhow::Result<()>;

    async fn term(self: Box<Self>) -> anyhow::Result<()>;
}

pub struct ReplicationMessage {
    pub delta: CommitDelta,
    ack: Box<dyn ReplicationAck>,
}

impl ReplicationMessage {
    pub fn new(delta: CommitDelta, ack: Box<dyn ReplicationAck>) -> Self {
        Self { delta, ack }
    }

    pub fn noop_ack(delta: CommitDelta) -> Self {
        Self {
            delta,
            ack: Box::new(NoopReplicationAck),
        }
    }

    pub fn into_parts(self) -> (CommitDelta, Box<dyn ReplicationAck>) {
        (self.delta, self.ack)
    }
}

pub struct NoopReplicationAck;

#[async_trait]
impl ReplicationAck for NoopReplicationAck {
    async fn ack(self: Box<Self>) -> anyhow::Result<()> {
        Ok(())
    }

    async fn nak(self: Box<Self>) -> anyhow::Result<()> {
        Ok(())
    }

    async fn term(self: Box<Self>) -> anyhow::Result<()> {
        Ok(())
    }
}

/// Abstraction over the transport that carries [`CommitDelta`]s between
/// the Primary node and Replica nodes.
///
/// The Primary calls [`publish`] after each commit. Replicas call [`subscribe`]
/// to get an ordered stream of deltas starting from a given timestamp.
#[async_trait]
pub trait DistributedLog: Send + Sync + 'static {
    /// Publish a committed delta to the log.
    ///
    /// Must be durable: once this returns Ok, Replicas are guaranteed to
    /// eventually see this delta.
    async fn publish(&self, delta: CommitDelta) -> anyhow::Result<()>;

    /// Subscribe to deltas starting after `from_ts`. Returns an ordered stream
    /// that blocks when caught up, resuming when new deltas arrive.
    async fn subscribe(
        &self,
        from_ts: Timestamp,
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<ReplicationMessage>>>;

    /// Subscribe to deltas starting after `from_ts`, optionally restricting
    /// delivery to specific source partitions.
    ///
    /// Implementations that do not support filtering can fall back to
    /// [`subscribe`] and perform any filtering client-side.
    async fn subscribe_filtered(
        &self,
        from_ts: Timestamp,
        _source_partitions: Option<Vec<PartitionId>>,
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<ReplicationMessage>>> {
        self.subscribe(from_ts).await
    }
}

/// No-op implementation for single-node deployments. `publish` does nothing,
/// `subscribe` returns a stream that never yields.
pub struct NoopDistributedLog;

#[async_trait]
impl DistributedLog for NoopDistributedLog {
    async fn publish(&self, _delta: CommitDelta) -> anyhow::Result<()> {
        Ok(())
    }

    async fn subscribe(
        &self,
        _from_ts: Timestamp,
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<ReplicationMessage>>> {
        Ok(Box::pin(futures::stream::pending()))
    }
}

impl CommitDelta {
    pub fn touched_table_names(&self) -> BTreeSet<TableName> {
        self.tablet_id_to_table_name.values().cloned().collect()
    }
}

#[cfg(any(test, feature = "testing"))]
pub mod testing {
    use std::sync::Arc;

    use async_trait::async_trait;
    use common::types::Timestamp;
    use futures::stream::BoxStream;
    use parking_lot::Mutex;
    use tokio::sync::broadcast;
    use tokio_stream::{
        wrappers::BroadcastStream,
        StreamExt,
    };

    use super::{
        CommitDelta,
        DistributedLog,
        ReplicationMessage,
    };

    /// In-memory [`DistributedLog`] for testing. Stores deltas in a Vec and
    /// notifies subscribers via a broadcast channel.
    pub struct InMemoryDistributedLog {
        deltas: Arc<Mutex<Vec<CommitDelta>>>,
        sender: broadcast::Sender<CommitDelta>,
    }

    impl InMemoryDistributedLog {
        pub fn new() -> Self {
            let (sender, _) = broadcast::channel(4096);
            Self {
                deltas: Arc::new(Mutex::new(Vec::new())),
                sender,
            }
        }

        /// Returns all deltas published so far.
        pub fn deltas(&self) -> Vec<CommitDelta> {
            self.deltas.lock().clone()
        }
    }

    #[async_trait]
    impl DistributedLog for InMemoryDistributedLog {
        async fn publish(&self, delta: CommitDelta) -> anyhow::Result<()> {
            self.deltas.lock().push(delta.clone());
            let _ = self.sender.send(delta);
            Ok(())
        }

        async fn subscribe(
            &self,
            from_ts: Timestamp,
        ) -> anyhow::Result<BoxStream<'static, anyhow::Result<ReplicationMessage>>> {
            let existing: Vec<CommitDelta> = self
                .deltas
                .lock()
                .iter()
                .filter(|d| d.ts > from_ts)
                .cloned()
                .collect();

            let receiver = self.sender.subscribe();
            let broadcast_stream =
                BroadcastStream::new(receiver).filter_map(move |result| match result {
                    Ok(delta) if delta.ts > from_ts => {
                        Some(Ok(ReplicationMessage::noop_ack(delta)))
                    },
                    Ok(_) => None,
                    Err(e) => Some(Err(anyhow::anyhow!("broadcast lag: {e}"))),
                });

            let existing_stream = futures::stream::iter(
                existing
                    .into_iter()
                    .map(ReplicationMessage::noop_ack)
                    .map(Ok),
            );
            let combined = existing_stream.chain(broadcast_stream);
            Ok(Box::pin(combined))
        }
    }
}

#[cfg(test)]
mod tests {
    use std::{
        collections::BTreeMap,
        sync::Arc,
    };

    use common::types::Timestamp;
    use value::TableName;

    use crate::{
        commit_delta::CommitDelta,
        write_log::WriteSource,
    };

    #[test]
    fn touched_table_names_collects_unique_tables() {
        let messages: TableName = "messages".parse().unwrap();
        let tasks: TableName = "tasks".parse().unwrap();
        let mut tablet_id_to_table_name = BTreeMap::new();
        tablet_id_to_table_name.insert(value::TabletId::MIN, messages.clone());
        tablet_id_to_table_name.insert(value::TabletId::MAX, tasks.clone());
        let delta = CommitDelta {
            ts: Timestamp::MIN,
            document_writes: Arc::new(Vec::new()),
            document_updates: Vec::new(),
            index_writes: Arc::new(Vec::new()),
            write_source: WriteSource::unknown(),
            write_bytes: 0,
            tablet_id_to_table_name,
            source_partition: None,
        };

        assert_eq!(
            delta.touched_table_names(),
            [messages, tasks].into_iter().collect()
        );
    }
}
