//! The [`CommitDelta`] captures everything that changed in a single committed
//! transaction. It is the unit of replication: the Primary publishes deltas to
//! a distributed log, and Replicas consume them to update their local state.
//!
//! This module also defines the [`DistributedLog`] trait — the abstraction over
//! whatever transport carries deltas between nodes.

use std::{
    collections::{
        BTreeMap,
        BTreeSet,
    },
    error::Error,
    fmt,
    sync::{
        atomic::{
            AtomicBool,
            Ordering,
        },
        Arc,
    },
    time::Duration,
};

use async_trait::async_trait;
use common::{
    document::DocumentUpdate,
    persistence::{
        DocumentLogEntry,
        PersistenceIndexEntry,
    },
    types::Timestamp,
};
use futures::stream::BoxStream;
use value::{
    TableName,
    TableNamespace,
    TabletId,
};

use crate::{
    partition::PartitionId,
    write_log::WriteSource,
};

/// Everything that changed in a single committed transaction.
///
/// Produced by the Committer after a successful commit. Contains enough
/// information for a Replica to:
/// 1. Update its [`SnapshotManager`] (via document_updates)
/// 2. Append to its local [`WriteLog`] (for subscription invalidation)
/// 3. Maintain ordering (via the commit timestamp)
#[derive(Clone, Debug)]
pub struct CommitDelta {
    /// The commit timestamp assigned by the source partition's Committer.
    ///
    /// Receivers may translate this into a later local apply timestamp for
    /// their own MVCC/write-log state, but this value remains the origin
    /// timestamp used for source-partition freshness watermarks. Exact
    /// redelivery idempotency uses [`ReplicationTransportId`] instead.
    pub ts: Timestamp,

    /// Document writes for persistence replay. Contains document ID, new value,
    /// and previous timestamp.
    pub document_writes: Arc<Vec<DocumentLogEntry>>,

    /// Document updates for snapshot replication. Contains old and new document
    /// values, which the Replica needs to update its SnapshotManager
    /// (table registry, index registry, schemas, etc.).
    pub document_updates: Vec<DocumentUpdate>,

    /// Index updates generated by this commit.
    pub index_writes: Arc<Vec<PersistenceIndexEntry>>,

    /// The source of the write (e.g. which mutation function triggered it).
    pub write_source: WriteSource,

    /// Total bytes written to persistence.
    pub write_bytes: u64,

    /// Stable identity for every tablet referenced by this delta.
    ///
    /// Table names alone are insufficient because component-scoped system
    /// tables reuse names such as `_modules` and `_schemas`. Replicas must map
    /// by the source component namespace and table name together.
    pub tablet_id_to_table_identity: BTreeMap<TabletId, DeltaTableIdentity>,

    /// Partition that originated this replicated event.
    ///
    /// Used to advance per-partition freshness frontiers on replicas, so
    /// remote reads can prove they were validated against a sufficiently
    /// up-to-date replica state.
    pub source_partition: Option<PartitionId>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DeltaTableIdentity {
    pub namespace: TableNamespace,
    pub table_name: TableName,
}

impl DeltaTableIdentity {
    pub fn new(namespace: TableNamespace, table_name: TableName) -> Self {
        Self {
            namespace,
            table_name,
        }
    }
}

/// Stable origin of a Raft-accepted delta persisted for later NATS delivery.
///
/// `source_node` is the configured logical backend name, not a network
/// address. Keeping all three fields lets a promoted follower replay the
/// original producer identity without fabricating its own origin.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RaftNatsOutboxOrigin {
    pub source_node: String,
    pub source_raft_node_id: u64,
    pub source_partition: PartitionId,
}

impl RaftNatsOutboxOrigin {
    pub fn new(
        source_node: String,
        source_raft_node_id: u64,
        source_partition: PartitionId,
    ) -> anyhow::Result<Self> {
        anyhow::ensure!(
            !source_node.is_empty(),
            "Raft->NATS outbox origin requires a non-empty logical source node",
        );
        Ok(Self {
            source_node,
            source_raft_node_id,
            source_partition,
        })
    }
}

#[async_trait]
pub trait ReplicationAck: Send + 'static {
    async fn ack(self: Box<Self>) -> anyhow::Result<()>;

    async fn nak(self: Box<Self>) -> anyhow::Result<()>;

    async fn nak_with_delay(self: Box<Self>, delay: Duration) -> anyhow::Result<()>;

    async fn term(self: Box<Self>) -> anyhow::Result<()>;
}

#[derive(Debug)]
pub struct RetryableReplicaApplyError {
    message: String,
}

impl RetryableReplicaApplyError {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl fmt::Display for RetryableReplicaApplyError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.message)
    }
}

impl Error for RetryableReplicaApplyError {}

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ReplicationPoisonKind {
    RetentionGap,
    MalformedEnvelope,
    UnsupportedEnvelopeVersion,
    InvalidDeltaPayload,
    DeterministicApplyFailure,
}

/// Durable evidence that a replica cannot prove it has applied a contiguous
/// replication prefix. Serving past this point could expose stale reads or
/// validate writes against incomplete state, so callers must fail the node
/// closed and rebootstrap its local persistence.
#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
pub struct ReplicationPoisonGap {
    pub kind: ReplicationPoisonKind,
    pub consumer: Option<String>,
    pub subject: Option<String>,
    pub stream_sequence: Option<u64>,
    pub source_node: Option<String>,
    pub source_partition: Option<u32>,
    pub origin_ts: Option<u64>,
    pub reason: String,
}

impl ReplicationPoisonGap {
    pub fn new(
        kind: ReplicationPoisonKind,
        consumer: Option<String>,
        subject: Option<String>,
        stream_sequence: Option<u64>,
        source_node: Option<String>,
        source_partition: Option<PartitionId>,
        origin_ts: Option<Timestamp>,
        reason: impl Into<String>,
    ) -> Self {
        Self {
            kind,
            consumer,
            subject,
            stream_sequence,
            source_node,
            source_partition: source_partition.map(|partition| partition.0),
            origin_ts: origin_ts.map(u64::from),
            reason: reason.into(),
        }
    }
}

impl fmt::Display for ReplicationPoisonGap {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "replication poison gap ({:?}): consumer={:?}, subject={:?}, stream_sequence={:?}, \
             source_node={:?}, source_partition={:?}, origin_ts={:?}: {}",
            self.kind,
            self.consumer,
            self.subject,
            self.stream_sequence,
            self.source_node,
            self.source_partition,
            self.origin_ts,
            self.reason,
        )
    }
}

impl Error for ReplicationPoisonGap {}

pub fn replication_poison_gap(error: &anyhow::Error) -> Option<&ReplicationPoisonGap> {
    error.downcast_ref::<ReplicationPoisonGap>()
}

pub struct ReplicationMessage {
    pub delta: CommitDelta,
    transport_id: Option<ReplicationTransportId>,
    ack: Box<dyn ReplicationAck>,
}

/// Durable identity for one transport delivery of a replication message.
///
/// This is intentionally separate from [`CommitDelta::ts`]. The origin commit
/// timestamp is a visibility/freshness watermark. A transport id is the thing
/// that lets a replica distinguish a redelivered old JetStream message from a
/// first-time late replay of an older origin timestamp.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct ReplicationTransportId {
    stream_sequence: u64,
}

impl ReplicationTransportId {
    pub fn new(stream_sequence: u64) -> Self {
        Self { stream_sequence }
    }

    pub fn stream_sequence(self) -> u64 {
        self.stream_sequence
    }
}

impl ReplicationMessage {
    pub fn new(delta: CommitDelta, ack: Box<dyn ReplicationAck>) -> Self {
        Self {
            delta,
            transport_id: None,
            ack,
        }
    }

    pub fn new_with_transport_id(
        delta: CommitDelta,
        transport_id: ReplicationTransportId,
        ack: Box<dyn ReplicationAck>,
    ) -> Self {
        Self {
            delta,
            transport_id: Some(transport_id),
            ack,
        }
    }

    pub fn noop_ack(delta: CommitDelta) -> Self {
        Self {
            delta,
            transport_id: None,
            ack: Box::new(NoopReplicationAck),
        }
    }

    pub fn noop_ack_with_transport_id(
        delta: CommitDelta,
        transport_id: ReplicationTransportId,
    ) -> Self {
        Self {
            delta,
            transport_id: Some(transport_id),
            ack: Box::new(NoopReplicationAck),
        }
    }

    pub fn into_parts(
        self,
    ) -> (
        CommitDelta,
        Option<ReplicationTransportId>,
        Box<dyn ReplicationAck>,
    ) {
        (self.delta, self.transport_id, self.ack)
    }
}

pub struct NoopReplicationAck;

#[async_trait]
impl ReplicationAck for NoopReplicationAck {
    async fn ack(self: Box<Self>) -> anyhow::Result<()> {
        Ok(())
    }

    async fn nak(self: Box<Self>) -> anyhow::Result<()> {
        Ok(())
    }

    async fn nak_with_delay(self: Box<Self>, _delay: Duration) -> anyhow::Result<()> {
        Ok(())
    }

    async fn term(self: Box<Self>) -> anyhow::Result<()> {
        Ok(())
    }
}

/// Abstraction over the transport that carries [`CommitDelta`]s between
/// the Primary node and Replica nodes.
///
/// The Primary calls [`publish`] after each commit. Replicas call [`subscribe`]
/// to get an ordered stream of deltas starting from a given timestamp.
#[async_trait]
pub trait DistributedLog: Send + Sync + 'static {
    /// Whether source-partition commits must use the durable persistence
    /// outbox instead of publishing on the commit hot path.
    ///
    /// Remote transports default to the safer outbox behavior. In-process and
    /// no-op implementations can opt out because they do not incur a network
    /// availability dependency.
    fn requires_commit_outbox(&self) -> bool {
        true
    }

    /// Stable logical name encoded by this transport for self-filtering.
    fn source_node(&self) -> Option<String> {
        None
    }

    /// Publish a committed delta to the log.
    ///
    /// Must be durable: once this returns Ok, Replicas are guaranteed to
    /// eventually see this delta.
    async fn publish(&self, delta: CommitDelta) -> anyhow::Result<()>;

    /// Publish a durable outbox delta while preserving the original Raft
    /// producer identity. Transport-neutral test logs may treat this like a
    /// normal publish; remote transports must override it when origin affects
    /// wire semantics.
    async fn publish_with_origin(
        &self,
        delta: CommitDelta,
        _origin: RaftNatsOutboxOrigin,
    ) -> anyhow::Result<()> {
        self.publish(delta).await
    }

    /// Subscribe to deltas starting after `from_ts`. Returns an ordered stream
    /// that blocks when caught up, resuming when new deltas arrive.
    async fn subscribe(
        &self,
        from_ts: Timestamp,
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<ReplicationMessage>>>;

    /// Subscribe to deltas starting after `from_ts`, optionally restricting
    /// delivery to specific source partitions.
    ///
    /// Implementations that do not support filtering can fall back to
    /// [`subscribe`] and perform any filtering client-side.
    async fn subscribe_filtered(
        &self,
        from_ts: Timestamp,
        _source_partitions: Option<Vec<PartitionId>>,
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<ReplicationMessage>>> {
        self.subscribe(from_ts).await
    }
}

/// No-op implementation for single-node deployments. `publish` does nothing,
/// `subscribe` returns a stream that never yields.
pub struct NoopDistributedLog;

#[async_trait]
impl DistributedLog for NoopDistributedLog {
    fn requires_commit_outbox(&self) -> bool {
        false
    }

    async fn publish(&self, _delta: CommitDelta) -> anyhow::Result<()> {
        Ok(())
    }

    async fn subscribe(
        &self,
        _from_ts: Timestamp,
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<ReplicationMessage>>> {
        Ok(Box::pin(futures::stream::pending()))
    }
}

/// Suppresses bootstrap-candidate deltas until canonical cluster genesis has
/// been confirmed. Candidate state is intentionally local and must never enter
/// the shared replication stream.
pub struct ClusterGenesisGatedDistributedLog {
    inner: Arc<dyn DistributedLog>,
    ready: Arc<AtomicBool>,
}

impl ClusterGenesisGatedDistributedLog {
    pub fn new(inner: Arc<dyn DistributedLog>, ready: Arc<AtomicBool>) -> Self {
        Self { inner, ready }
    }
}

#[async_trait]
impl DistributedLog for ClusterGenesisGatedDistributedLog {
    fn requires_commit_outbox(&self) -> bool {
        // Candidate bootstrap state must be neither published nor retained for
        // publication after canonical genesis is selected.
        self.ready.load(Ordering::SeqCst) && self.inner.requires_commit_outbox()
    }

    fn source_node(&self) -> Option<String> {
        self.inner.source_node()
    }

    async fn publish(&self, delta: CommitDelta) -> anyhow::Result<()> {
        if !self.ready.load(Ordering::SeqCst) {
            return Ok(());
        }
        self.inner.publish(delta).await
    }

    async fn publish_with_origin(
        &self,
        delta: CommitDelta,
        origin: RaftNatsOutboxOrigin,
    ) -> anyhow::Result<()> {
        if !self.ready.load(Ordering::SeqCst) {
            return Ok(());
        }
        self.inner.publish_with_origin(delta, origin).await
    }

    async fn subscribe(
        &self,
        from_ts: Timestamp,
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<ReplicationMessage>>> {
        self.inner.subscribe(from_ts).await
    }

    async fn subscribe_filtered(
        &self,
        from_ts: Timestamp,
        source_partitions: Option<Vec<PartitionId>>,
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<ReplicationMessage>>> {
        self.inner
            .subscribe_filtered(from_ts, source_partitions)
            .await
    }
}

impl CommitDelta {
    pub fn touched_table_names(&self) -> BTreeSet<TableName> {
        self.tablet_id_to_table_identity
            .values()
            .map(|identity| identity.table_name.clone())
            .collect()
    }
}

#[cfg(any(test, feature = "testing"))]
pub mod testing {
    use std::sync::Arc;

    use async_trait::async_trait;
    use common::types::Timestamp;
    use futures::stream::BoxStream;
    use parking_lot::Mutex;
    use tokio::sync::broadcast;
    use tokio_stream::{
        wrappers::BroadcastStream,
        StreamExt,
    };

    use super::{
        CommitDelta,
        DistributedLog,
        ReplicationMessage,
    };

    /// In-memory [`DistributedLog`] for testing. Stores deltas in a Vec and
    /// notifies subscribers via a broadcast channel.
    pub struct InMemoryDistributedLog {
        deltas: Arc<Mutex<Vec<CommitDelta>>>,
        sender: broadcast::Sender<CommitDelta>,
    }

    impl InMemoryDistributedLog {
        pub fn new() -> Self {
            let (sender, _) = broadcast::channel(4096);
            Self {
                deltas: Arc::new(Mutex::new(Vec::new())),
                sender,
            }
        }

        /// Returns all deltas published so far.
        pub fn deltas(&self) -> Vec<CommitDelta> {
            self.deltas.lock().clone()
        }
    }

    #[async_trait]
    impl DistributedLog for InMemoryDistributedLog {
        fn requires_commit_outbox(&self) -> bool {
            false
        }

        async fn publish(&self, delta: CommitDelta) -> anyhow::Result<()> {
            self.deltas.lock().push(delta.clone());
            let _ = self.sender.send(delta);
            Ok(())
        }

        async fn subscribe(
            &self,
            from_ts: Timestamp,
        ) -> anyhow::Result<BoxStream<'static, anyhow::Result<ReplicationMessage>>> {
            let existing: Vec<CommitDelta> = self
                .deltas
                .lock()
                .iter()
                .filter(|d| d.ts > from_ts)
                .cloned()
                .collect();

            let receiver = self.sender.subscribe();
            let broadcast_stream =
                BroadcastStream::new(receiver).filter_map(move |result| match result {
                    Ok(delta) if delta.ts > from_ts => {
                        Some(Ok(ReplicationMessage::noop_ack(delta)))
                    },
                    Ok(_) => None,
                    Err(e) => Some(Err(anyhow::anyhow!("broadcast lag: {e}"))),
                });

            let existing_stream = futures::stream::iter(
                existing
                    .into_iter()
                    .map(ReplicationMessage::noop_ack)
                    .map(Ok),
            );
            let combined = existing_stream.chain(broadcast_stream);
            Ok(Box::pin(combined))
        }
    }
}

#[cfg(test)]
mod tests {
    use std::{
        collections::BTreeMap,
        sync::{
            atomic::{
                AtomicBool,
                Ordering,
            },
            Arc,
        },
    };

    use common::types::Timestamp;
    use value::TableName;

    use crate::{
        commit_delta::{
            testing::InMemoryDistributedLog,
            ClusterGenesisGatedDistributedLog,
            CommitDelta,
            DistributedLog,
        },
        write_log::WriteSource,
    };

    fn test_delta() -> CommitDelta {
        CommitDelta {
            ts: Timestamp::MIN,
            document_writes: Arc::new(Vec::new()),
            document_updates: Vec::new(),
            index_writes: Arc::new(Vec::new()),
            write_source: WriteSource::unknown(),
            write_bytes: 0,
            tablet_id_to_table_identity: BTreeMap::new(),
            source_partition: None,
        }
    }

    #[tokio::test]
    async fn cluster_genesis_gate_suppresses_candidate_deltas() {
        let inner = Arc::new(InMemoryDistributedLog::new());
        let ready = Arc::new(AtomicBool::new(false));
        let gated = ClusterGenesisGatedDistributedLog::new(inner.clone(), ready.clone());

        assert!(!gated.requires_commit_outbox());
        gated.publish(test_delta()).await.unwrap();
        assert!(inner.deltas().is_empty());

        ready.store(true, Ordering::SeqCst);
        assert!(gated.requires_commit_outbox());
        gated.publish(test_delta()).await.unwrap();
        assert_eq!(inner.deltas().len(), 1);
    }

    #[test]
    fn touched_table_names_collects_unique_tables() {
        let messages: TableName = "messages".parse().unwrap();
        let tasks: TableName = "tasks".parse().unwrap();
        let mut tablet_id_to_table_identity = BTreeMap::new();
        tablet_id_to_table_identity.insert(
            value::TabletId::MIN,
            super::DeltaTableIdentity::new(value::TableNamespace::Global, messages.clone()),
        );
        tablet_id_to_table_identity.insert(
            value::TabletId::MAX,
            super::DeltaTableIdentity::new(value::TableNamespace::Global, tasks.clone()),
        );
        let delta = CommitDelta {
            ts: Timestamp::MIN,
            document_writes: Arc::new(Vec::new()),
            document_updates: Vec::new(),
            index_writes: Arc::new(Vec::new()),
            write_source: WriteSource::unknown(),
            write_bytes: 0,
            tablet_id_to_table_identity,
            source_partition: None,
        };

        assert_eq!(
            delta.touched_table_names(),
            [messages, tasks].into_iter().collect()
        );
    }
}
