//! Two-Phase Commit (2PC) for cross-partition writes.
//!
//! When a mutation writes to tables on multiple partitions, the
//! single-partition fast path (TiDB 1PC pattern) cannot be used. Instead, we
//! use Vitess's 2PC protocol:
//!
//! 1. Coordinator detects cross-partition writes
//! 2. Sends Prepare to each partition's Committer
//! 3. Each Committer validates OCC, stages writes, persists redo log
//! 4. Coordinator records commit/rollback decision in NATS KV
//! 5. Sends CommitPrepared/RollbackPrepared to participants
//!
//! References:
//!   - Vitess: https://vitess.io/docs/22.0/reference/features/distributed-transaction/
//!   - TiDB 1PC: https://pingcap.github.io/tidb-dev-guide/understand-tidb/1pc.html
//!   - CockroachDB: https://www.cockroachlabs.com/blog/parallel-commits/

use std::{
    collections::BTreeMap,
    time::Duration,
};

use anyhow::Context;
use async_nats::jetstream::kv::Store;
use async_trait::async_trait;
use common::{
    bootstrap_model::index::database_index::IndexedFields,
    document::DocumentUpdateWithPrevTs,
    grpc::ClusterGrpcAuth,
    interval::IntervalSet,
    query::FilterValue,
    types::{
        IndexDescriptor,
        RepeatableTimestamp,
        TabletIndexName,
        Timestamp,
    },
};
use pb::{
    common::RepeatableTimestamp as RepeatableTimestampProto,
    replication::{
        two_phase_commit_service_client::TwoPhaseCommitServiceClient as TonicTwoPcClient,
        TwoPcCommitRequest,
        TwoPcFilterConditionRead,
        TwoPcIndexedRead,
        TwoPcParticipantTransaction as TwoPcParticipantTransactionProto,
        TwoPcPrepareRequest,
        TwoPcPrepareResponse,
        TwoPcRollbackRequest,
        TwoPcSearchRead,
        TwoPcTabletMetadata,
        TwoPcTextQueryTermRead,
    },
    searchlight,
};
use prost::Message;
use search::{
    query::{
        FuzzyDistance,
        QueryReads,
        TextQueryTerm,
    },
    FilterConditionRead,
    TextQueryTermRead,
};
use serde::{
    Deserialize,
    Serialize,
};
use tonic::{
    transport::Channel,
    Request,
};
use value::{
    FieldPath,
    TableName,
    TableNamespace,
    TableNumber,
    TabletId,
};

use crate::{
    partition::{
        routed_partition_for_table,
        PartitionId,
        PartitionMap,
    },
    reads::{
        IndexReads,
        ReadSet,
    },
    transaction::FinalTransaction,
    write_log::WriteSource,
};

/// Globally unique transaction ID for 2PC.
/// Generated by the coordinator using UUID v4.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TwoPhaseTransactionId(pub String);

impl TwoPhaseTransactionId {
    pub fn new() -> Self {
        Self(uuid::Uuid::new_v4().to_string())
    }
}

impl std::fmt::Display for TwoPhaseTransactionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// State of a 2PC transaction stored in NATS KV.
/// This is the commit decision record — the point of no return.
/// Follows Vitess's Metadata Manager (MM) pattern.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum TwoPhaseDecision {
    /// All participants prepared successfully. Commit.
    Committed {
        commit_ts: u64,
        participants: Vec<u32>,
    },
    /// A participant failed to prepare, or coordinator timed out. Rollback.
    RolledBack {
        reason: String,
        participants: Vec<u32>,
    },
}

/// Result from a successful Prepare on a participant.
#[derive(Debug)]
pub struct PrepareResult {
    /// The timestamp assigned to this partition's portion of the transaction.
    pub prepare_ts: Timestamp,
}

/// Redo log entry persisted during Prepare for crash recovery.
/// If a node crashes after Prepare but before CommitPrepared/RollbackPrepared,
/// the transaction watcher reads the redo log and resolves the transaction
/// by checking the decision record in NATS KV.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TwoPhaseRedoEntry {
    pub transaction_id: String,
    pub prepare_ts: u64,
    pub partition_id: u32,
    pub write_source: Option<String>,
    pub participant_transaction_hex: String,
}

impl TwoPhaseRedoEntry {
    pub fn new(
        transaction_id: &TwoPhaseTransactionId,
        prepare_ts: Timestamp,
        partition_id: PartitionId,
        transaction: ParticipantTransaction,
        write_source: &WriteSource,
    ) -> anyhow::Result<Self> {
        let proto = TwoPcParticipantTransactionProto::try_from(transaction)?;
        let mut bytes = Vec::new();
        proto
            .encode(&mut bytes)
            .context("2PC: Failed to encode participant transaction redo")?;
        Ok(Self {
            transaction_id: transaction_id.0.clone(),
            prepare_ts: u64::from(prepare_ts),
            partition_id: partition_id.0,
            write_source: write_source.as_str().map(str::to_string),
            participant_transaction_hex: hex::encode(bytes),
        })
    }

    pub fn transaction_id(&self) -> TwoPhaseTransactionId {
        TwoPhaseTransactionId(self.transaction_id.clone())
    }

    pub fn prepare_ts(&self) -> anyhow::Result<Timestamp> {
        self.prepare_ts.try_into()
    }

    pub fn partition_id(&self) -> PartitionId {
        PartitionId(self.partition_id)
    }

    pub fn write_source(&self) -> WriteSource {
        WriteSource::from(self.write_source.clone())
    }

    pub fn participant_transaction(&self) -> anyhow::Result<ParticipantTransaction> {
        let bytes = hex::decode(&self.participant_transaction_hex)
            .context("2PC: Failed to decode participant transaction redo")?;
        let proto = TwoPcParticipantTransactionProto::decode(bytes.as_slice())
            .context("2PC: Failed to parse participant transaction redo")?;
        ParticipantTransaction::try_from(proto)
    }
}

#[cfg(any(test, feature = "testing"))]
pub mod testing {
    use std::sync::Arc;

    use parking_lot::Mutex;

    use super::*;

    #[derive(Clone, Default)]
    pub struct InMemoryTwoPhaseDecisionLog {
        decisions: Arc<Mutex<BTreeMap<String, TwoPhaseDecision>>>,
    }

    impl InMemoryTwoPhaseDecisionLog {
        pub fn new() -> Self {
            Self::default()
        }

        pub fn decisions(&self) -> BTreeMap<String, TwoPhaseDecision> {
            self.decisions.lock().clone()
        }
    }

    #[async_trait]
    impl TwoPhaseDecisionLog for InMemoryTwoPhaseDecisionLog {
        async fn write_decision(
            &self,
            transaction_id: &TwoPhaseTransactionId,
            decision: &TwoPhaseDecision,
        ) -> anyhow::Result<()> {
            self.decisions
                .lock()
                .insert(transaction_id.0.clone(), decision.clone());
            Ok(())
        }

        async fn delete_decision(
            &self,
            transaction_id: &TwoPhaseTransactionId,
        ) -> anyhow::Result<()> {
            self.decisions.lock().remove(&transaction_id.0);
            Ok(())
        }
    }
}

/// NATS KV key prefix for 2PC decision records.
pub const TWO_PHASE_KV_PREFIX: &str = "2pc_";

/// NATS KV bucket for 2PC state.
pub const TWO_PHASE_KV_BUCKET: &str = "convex_2pc";

/// Retain resolved 2PC decision records long enough for watcher recovery.
pub const TWO_PHASE_DECISION_TTL_SECS: u64 = 3600;

/// Timeout for prepared transactions before the watcher rolls them back.
pub const PREPARE_TIMEOUT_SECS: u64 = 30;

pub fn two_phase_decision_key(transaction_id: &TwoPhaseTransactionId) -> String {
    format!("{TWO_PHASE_KV_PREFIX}{}", transaction_id.0)
}

#[async_trait]
pub trait TwoPhaseDecisionLog: Send + Sync + 'static {
    async fn write_decision(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        decision: &TwoPhaseDecision,
    ) -> anyhow::Result<()>;

    async fn delete_decision(&self, transaction_id: &TwoPhaseTransactionId) -> anyhow::Result<()>;
}

pub struct NoopTwoPhaseDecisionLog;

#[async_trait]
impl TwoPhaseDecisionLog for NoopTwoPhaseDecisionLog {
    async fn write_decision(
        &self,
        _transaction_id: &TwoPhaseTransactionId,
        _decision: &TwoPhaseDecision,
    ) -> anyhow::Result<()> {
        Ok(())
    }

    async fn delete_decision(&self, _transaction_id: &TwoPhaseTransactionId) -> anyhow::Result<()> {
        Ok(())
    }
}

#[derive(Clone)]
pub struct NatsTwoPhaseDecisionLog {
    kv: Store,
}

impl NatsTwoPhaseDecisionLog {
    pub async fn connect(nats_url: &str) -> anyhow::Result<Self> {
        let _ = rustls::crypto::ring::default_provider().install_default();
        let client = async_nats::connect(nats_url)
            .await
            .with_context(|| format!("2PC: Failed to connect to NATS at {nats_url}"))?;
        let jetstream = async_nats::jetstream::new(client);
        let kv = jetstream
            .create_key_value(async_nats::jetstream::kv::Config {
                bucket: TWO_PHASE_KV_BUCKET.to_string(),
                history: 1,
                max_age: Duration::from_secs(TWO_PHASE_DECISION_TTL_SECS),
                ..Default::default()
            })
            .await
            .context("2PC: Failed to create decision KV bucket")?;
        Ok(Self { kv })
    }
}

#[async_trait]
impl TwoPhaseDecisionLog for NatsTwoPhaseDecisionLog {
    async fn write_decision(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        decision: &TwoPhaseDecision,
    ) -> anyhow::Result<()> {
        let payload = serde_json::to_vec(decision)
            .with_context(|| format!("2PC: Failed to serialize decision for {transaction_id}"))?;
        self.kv
            .put(two_phase_decision_key(transaction_id), payload.into())
            .await
            .with_context(|| format!("2PC: Failed to write decision for {transaction_id}"))?;
        Ok(())
    }

    async fn delete_decision(&self, transaction_id: &TwoPhaseTransactionId) -> anyhow::Result<()> {
        self.kv
            .delete(two_phase_decision_key(transaction_id))
            .await
            .with_context(|| format!("2PC: Failed to delete decision for {transaction_id}"))?;
        Ok(())
    }
}

/// Partition-to-address mapping for gRPC communication.
/// Each entry maps a partition ID to the gRPC address of its owner node.
#[derive(Clone, Debug)]
pub struct NodeAddresses {
    addresses: BTreeMap<PartitionId, String>,
}

impl NodeAddresses {
    /// Parse from config string: "0=host:port,1=host:port"
    pub fn from_config(config: &str) -> Self {
        let mut addresses = BTreeMap::new();
        if !config.is_empty() {
            for pair in config.split(',') {
                let pair = pair.trim();
                if let Some((id, addr)) = pair.split_once('=') {
                    if let Ok(partition_id) = id.trim().parse::<u32>() {
                        addresses.insert(PartitionId(partition_id), addr.trim().to_string());
                    }
                }
            }
        }
        Self { addresses }
    }

    /// Get the gRPC address for a partition.
    pub fn address_for(&self, partition: PartitionId) -> Option<&str> {
        self.addresses.get(&partition).map(|s| s.as_str())
    }

    /// Get all known partitions.
    pub fn partitions(&self) -> Vec<PartitionId> {
        self.addresses.keys().copied().collect()
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ParticipantTabletMetadata {
    pub tablet_id: TabletId,
    pub namespace: TableNamespace,
    pub table_number: TableNumber,
    pub table_name: TableName,
}

#[derive(Clone, Debug)]
#[cfg_attr(any(test, feature = "testing"), derive(PartialEq))]
pub struct ParticipantTransaction {
    pub begin_timestamp: RepeatableTimestamp,
    pub tablet_metadata: BTreeMap<TabletId, ParticipantTabletMetadata>,
    pub reads: ReadSet,
    pub writes: Vec<DocumentUpdateWithPrevTs>,
}

impl ParticipantTransaction {
    pub fn from_final_transaction(
        transaction: &FinalTransaction,
        participant: PartitionId,
        write_indexes: &[usize],
        partition_map: &PartitionMap,
        write_source: &WriteSource,
    ) -> anyhow::Result<Self> {
        let selected_writes: Vec<_> = transaction
            .writes
            .coalesced_writes()
            .enumerate()
            .filter(|(index, _)| write_indexes.contains(index))
            .map(|(_, write)| write.clone())
            .collect();

        let belongs_to_participant = |tablet_id: TabletId| -> bool {
            let Ok(table_name) = transaction.table_mapping.tablet_name(tablet_id) else {
                return false;
            };
            match routed_partition_for_table(&table_name, partition_map, write_source) {
                Some(owner) => owner == participant,
                None => participant == partition_map.local_partition(),
            }
        };

        let indexed_reads = transaction
            .reads
            .read_set()
            .iter_indexed()
            .filter(|(index_name, _)| belongs_to_participant(*index_name.table()))
            .map(|(index_name, reads)| (index_name.clone(), reads.clone()))
            .collect();
        let search_reads = transaction
            .reads
            .read_set()
            .iter_search()
            .filter(|(index_name, _)| belongs_to_participant(*index_name.table()))
            .map(|(index_name, reads)| (index_name.clone(), reads.clone()))
            .collect();
        let reads = ReadSet::new(indexed_reads, search_reads);

        let mut tablet_metadata = BTreeMap::new();
        let mut record_tablet = |tablet_id: TabletId| -> anyhow::Result<()> {
            if tablet_metadata.contains_key(&tablet_id) {
                return Ok(());
            }
            let table_name = transaction.table_mapping.tablet_name(tablet_id)?;
            let table_number = transaction.table_mapping.tablet_number(tablet_id)?;
            let namespace = transaction.table_mapping.tablet_namespace(tablet_id)?;
            tablet_metadata.insert(
                tablet_id,
                ParticipantTabletMetadata {
                    tablet_id,
                    namespace,
                    table_number,
                    table_name,
                },
            );
            Ok(())
        };

        for (index_name, _) in reads.iter_indexed() {
            record_tablet(*index_name.table())?;
        }
        for (index_name, _) in reads.iter_search() {
            record_tablet(*index_name.table())?;
        }
        for write in &selected_writes {
            record_tablet(write.id.tablet_id)?;
        }

        Ok(Self {
            begin_timestamp: transaction.begin_timestamp,
            tablet_metadata,
            reads,
            writes: selected_writes,
        })
    }

    pub fn from_entire_final_transaction(transaction: &FinalTransaction) -> anyhow::Result<Self> {
        let selected_writes: Vec<_> = transaction.writes.coalesced_writes().cloned().collect();
        let mut tablet_metadata = BTreeMap::new();
        let mut record_tablet = |tablet_id: TabletId| -> anyhow::Result<()> {
            if tablet_metadata.contains_key(&tablet_id) {
                return Ok(());
            }
            let table_name = transaction.table_mapping.tablet_name(tablet_id)?;
            let table_number = transaction.table_mapping.tablet_number(tablet_id)?;
            let namespace = transaction.table_mapping.tablet_namespace(tablet_id)?;
            tablet_metadata.insert(
                tablet_id,
                ParticipantTabletMetadata {
                    tablet_id,
                    namespace,
                    table_number,
                    table_name,
                },
            );
            Ok(())
        };

        for (index_name, _) in transaction.reads.read_set().iter_indexed() {
            record_tablet(*index_name.table())?;
        }
        for (index_name, _) in transaction.reads.read_set().iter_search() {
            record_tablet(*index_name.table())?;
        }
        for write in &selected_writes {
            record_tablet(write.id.tablet_id)?;
        }

        Ok(Self {
            begin_timestamp: transaction.begin_timestamp,
            tablet_metadata,
            reads: transaction.reads.read_set().clone(),
            writes: selected_writes,
        })
    }

    pub fn augment_table_mapping(
        &self,
        table_mapping: &mut value::TableMapping,
    ) -> anyhow::Result<()> {
        for metadata in self.tablet_metadata.values() {
            if table_mapping.tablet_id_exists(metadata.tablet_id) {
                continue;
            }
            table_mapping.insert_tablet(
                metadata.tablet_id,
                metadata.namespace,
                metadata.table_number,
                metadata.table_name.clone(),
            );
        }
        Ok(())
    }
}

fn descriptor_to_index_name(
    tablet_id: TabletId,
    descriptor: String,
) -> anyhow::Result<TabletIndexName> {
    match descriptor.as_str() {
        "by_id" => Ok(TabletIndexName::by_id(tablet_id)),
        "by_creation_time" => Ok(TabletIndexName::by_creation_time(tablet_id)),
        _ => TabletIndexName::new(tablet_id, IndexDescriptor::new(descriptor)?),
    }
}

fn tablet_id_to_bytes(tablet_id: TabletId) -> Vec<u8> {
    tablet_id.0 .0.to_vec()
}

fn tablet_id_from_bytes(bytes: Vec<u8>) -> anyhow::Result<TabletId> {
    Ok(TabletId(bytes.try_into()?))
}

impl TryFrom<TwoPcParticipantTransactionProto> for ParticipantTransaction {
    type Error = anyhow::Error;

    fn try_from(value: TwoPcParticipantTransactionProto) -> anyhow::Result<Self> {
        let begin_timestamp = value
            .begin_timestamp
            .context("TwoPcParticipantTransaction missing begin_timestamp")?
            .try_into()?;

        let tablet_metadata = value
            .tablet_metadata
            .into_iter()
            .map(
                |TwoPcTabletMetadata {
                     tablet_id,
                     component_id,
                     table_number,
                     table_name,
                 }| {
                    let tablet_id = tablet_id_from_bytes(tablet_id)?;
                    let namespace = match component_id {
                        Some(component_id) => TableNamespace::ByComponent(component_id.parse()?),
                        None => TableNamespace::Global,
                    };
                    let table_number = table_number.try_into()?;
                    let table_name = table_name.parse::<TableName>()?;
                    Ok((
                        tablet_id,
                        ParticipantTabletMetadata {
                            tablet_id,
                            namespace,
                            table_number,
                            table_name,
                        },
                    ))
                },
            )
            .collect::<anyhow::Result<BTreeMap<_, _>>>()?;

        let indexed_reads = value
            .indexed_reads
            .into_iter()
            .map(
                |TwoPcIndexedRead {
                     tablet_id,
                     descriptor,
                     fields,
                     intervals,
                 }| {
                    let tablet_id = tablet_id_from_bytes(tablet_id)?;
                    let index_name = descriptor_to_index_name(tablet_id, descriptor)?;
                    let fields = fields
                        .into_iter()
                        .map(FieldPath::try_from)
                        .collect::<anyhow::Result<Vec<_>>>()?;
                    let intervals = IntervalSet::try_from(intervals)?;
                    Ok((
                        index_name,
                        IndexReads {
                            fields: IndexedFields::try_from(fields)?,
                            intervals,
                            stack_traces: None,
                        },
                    ))
                },
            )
            .collect::<anyhow::Result<BTreeMap<_, _>>>()?;

        let search_reads = value
            .search_reads
            .into_iter()
            .map(
                |TwoPcSearchRead {
                     tablet_id,
                     descriptor,
                     text_queries,
                     filter_conditions,
                 }| {
                    let tablet_id = tablet_id_from_bytes(tablet_id)?;
                    let index_name = descriptor_to_index_name(tablet_id, descriptor)?;
                    let text_queries = text_queries
                        .into_iter()
                        .map(
                            |TwoPcTextQueryTermRead { field_path, term }| -> anyhow::Result<_> {
                                let field_path = field_path
                                    .context("TwoPcTextQueryTermRead missing field_path")?
                                    .try_into()?;
                                let term = text_query_term_from_proto(
                                    term.context("TwoPcTextQueryTermRead missing term")?,
                                )?;
                                Ok(TextQueryTermRead::new(field_path, term))
                            },
                        )
                        .collect::<anyhow::Result<Vec<_>>>()?;
                    let filter_conditions = filter_conditions
                        .into_iter()
                        .map(
                            |TwoPcFilterConditionRead { field_path, value }| -> anyhow::Result<_> {
                                let field_path = field_path
                                    .context("TwoPcFilterConditionRead missing field_path")?
                                    .try_into()?;
                                Ok(FilterConditionRead::Must(
                                    field_path,
                                    FilterValue::from(value),
                                ))
                            },
                        )
                        .collect::<anyhow::Result<Vec<_>>>()?;
                    Ok((
                        index_name,
                        QueryReads::new(text_queries.into(), filter_conditions.into()),
                    ))
                },
            )
            .collect::<anyhow::Result<BTreeMap<_, _>>>()?;

        let writes = value
            .writes
            .into_iter()
            .map(DocumentUpdateWithPrevTs::try_from)
            .collect::<anyhow::Result<Vec<_>>>()?;

        Ok(Self {
            begin_timestamp,
            tablet_metadata,
            reads: ReadSet::new(indexed_reads, search_reads),
            writes,
        })
    }
}

impl TryFrom<ParticipantTransaction> for TwoPcParticipantTransactionProto {
    type Error = anyhow::Error;

    fn try_from(value: ParticipantTransaction) -> anyhow::Result<Self> {
        let indexed_reads = value
            .reads
            .iter_indexed()
            .map(|(index_name, reads)| TwoPcIndexedRead {
                tablet_id: tablet_id_to_bytes(*index_name.table()),
                descriptor: index_name.descriptor().to_string(),
                fields: Vec::<pb::common::FieldPath>::from(reads.fields.clone()),
                intervals: reads.intervals.clone().into(),
            })
            .collect();

        let search_reads = value
            .reads
            .iter_search()
            .map(|(index_name, reads)| -> anyhow::Result<TwoPcSearchRead> {
                Ok(TwoPcSearchRead {
                    tablet_id: tablet_id_to_bytes(*index_name.table()),
                    descriptor: index_name.descriptor().to_string(),
                    text_queries: reads
                        .text_queries
                        .iter()
                        .map(|read| {
                            Ok(TwoPcTextQueryTermRead {
                                field_path: Some(read.field_path.clone().into()),
                                term: Some(text_query_term_to_proto(read.term.clone())),
                            })
                        })
                        .collect::<anyhow::Result<Vec<_>>>()?,
                    filter_conditions: reads
                        .filter_conditions
                        .iter()
                        .map(|read| match read {
                            FilterConditionRead::Must(field_path, value) => {
                                Ok(TwoPcFilterConditionRead {
                                    field_path: Some(field_path.clone().into()),
                                    value: value.clone().into(),
                                })
                            },
                        })
                        .collect::<anyhow::Result<Vec<_>>>()?,
                })
            })
            .collect::<anyhow::Result<Vec<_>>>()?;

        let writes = value
            .writes
            .into_iter()
            .map(pb::common::DocumentUpdateWithPrevTs::try_from)
            .collect::<anyhow::Result<Vec<_>>>()?;

        Ok(TwoPcParticipantTransactionProto {
            begin_timestamp: Some(RepeatableTimestampProto::from(value.begin_timestamp)),
            tablet_metadata: value
                .tablet_metadata
                .into_values()
                .map(|metadata| TwoPcTabletMetadata {
                    tablet_id: tablet_id_to_bytes(metadata.tablet_id),
                    component_id: match metadata.namespace {
                        TableNamespace::Global => None,
                        TableNamespace::ByComponent(component_id) => Some(component_id.encode()),
                    },
                    table_number: u32::from(metadata.table_number),
                    table_name: metadata.table_name.to_string(),
                })
                .collect(),
            indexed_reads,
            search_reads,
            writes,
        })
    }
}

fn text_query_term_from_proto(value: searchlight::TextQueryTerm) -> anyhow::Result<TextQueryTerm> {
    match value.term_type {
        Some(searchlight::text_query_term::TermType::Exact(exact)) => {
            Ok(TextQueryTerm::Exact(exact.token))
        },
        Some(searchlight::text_query_term::TermType::Fuzzy(fuzzy)) => Ok(TextQueryTerm::Fuzzy {
            token: fuzzy.token,
            max_distance: FuzzyDistance::try_from(fuzzy.max_distance as u8)?,
            prefix: fuzzy.prefix,
        }),
        None => anyhow::bail!("TextQueryTerm missing term_type"),
    }
}

fn text_query_term_to_proto(value: TextQueryTerm) -> searchlight::TextQueryTerm {
    let term_type = match value {
        TextQueryTerm::Exact(token) => {
            searchlight::text_query_term::TermType::Exact(searchlight::ExactTextTerm { token })
        },
        TextQueryTerm::Fuzzy {
            token,
            max_distance,
            prefix,
        } => searchlight::text_query_term::TermType::Fuzzy(searchlight::FuzzyTextTerm {
            token,
            max_distance: u8::from(max_distance) as u32,
            prefix,
        }),
    };
    searchlight::TextQueryTerm {
        term_type: Some(term_type),
    }
}

/// gRPC client for reaching remote partitions' 2PC service.
pub struct TwoPhaseCommitGrpcClient {
    client: TonicTwoPcClient<Channel>,
    cluster_auth: Option<ClusterGrpcAuth>,
}

impl TwoPhaseCommitGrpcClient {
    pub async fn connect(addr: &str) -> anyhow::Result<Self> {
        Self::connect_inner(addr, None).await
    }

    pub async fn connect_with_auth(
        addr: &str,
        cluster_auth: ClusterGrpcAuth,
    ) -> anyhow::Result<Self> {
        Self::connect_inner(addr, Some(cluster_auth)).await
    }

    async fn connect_inner(
        addr: &str,
        cluster_auth: Option<ClusterGrpcAuth>,
    ) -> anyhow::Result<Self> {
        let normalized_addr = if addr.contains("://") {
            addr.to_string()
        } else {
            format!("http://{addr}")
        };
        let client = TonicTwoPcClient::connect(normalized_addr.clone())
            .await
            .with_context(|| format!("Failed to connect to 2PC service at {normalized_addr}"))?;
        Ok(Self {
            client,
            cluster_auth,
        })
    }

    fn request<T>(&self, message: T) -> Request<T> {
        match &self.cluster_auth {
            Some(auth) => auth.request(message),
            None => Request::new(message),
        }
    }

    pub async fn prepare(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        transaction: ParticipantTransaction,
        write_source: WriteSource,
        prepare_ts: Timestamp,
        placement_version: crate::partition::PlacementVersion,
    ) -> anyhow::Result<PrepareResult> {
        let request = TwoPcPrepareRequest {
            transaction_id: transaction_id.0.clone(),
            transaction: Some(transaction.try_into()?),
            write_source: write_source.as_str().unwrap_or_default().to_string(),
            prepare_ts: u64::from(prepare_ts),
            placement_version: u64::from(placement_version),
        };
        let response = self
            .client
            .clone()
            .prepare(self.request(request))
            .await
            .context("gRPC Prepare failed")?;
        let TwoPcPrepareResponse { prepare_ts } = response.into_inner();
        Ok(PrepareResult {
            prepare_ts: prepare_ts.try_into()?,
        })
    }

    pub async fn commit_prepared(
        &self,
        transaction_id: &TwoPhaseTransactionId,
    ) -> anyhow::Result<u64> {
        let request = TwoPcCommitRequest {
            transaction_id: transaction_id.0.clone(),
        };
        let response = self
            .client
            .clone()
            .commit_prepared(self.request(request))
            .await
            .context("gRPC CommitPrepared failed")?;
        Ok(response.into_inner().commit_ts)
    }

    pub async fn rollback_prepared(
        &self,
        transaction_id: &TwoPhaseTransactionId,
    ) -> anyhow::Result<()> {
        let request = TwoPcRollbackRequest {
            transaction_id: transaction_id.0.clone(),
        };
        self.client
            .clone()
            .rollback_prepared(self.request(request))
            .await
            .context("gRPC RollbackPrepared failed")?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_node_addresses_parsing() {
        let addrs = NodeAddresses::from_config("0=node-a:50051,1=node-b:50051");
        assert_eq!(addrs.address_for(PartitionId(0)), Some("node-a:50051"));
        assert_eq!(addrs.address_for(PartitionId(1)), Some("node-b:50051"));
        assert_eq!(addrs.address_for(PartitionId(2)), None);
    }

    #[test]
    fn test_node_addresses_empty() {
        let addrs = NodeAddresses::from_config("");
        assert!(addrs.partitions().is_empty());
    }

    #[test]
    fn test_two_phase_transaction_id() {
        let id1 = TwoPhaseTransactionId::new();
        let id2 = TwoPhaseTransactionId::new();
        assert_ne!(id1, id2);
    }

    #[test]
    fn test_decision_serialization() {
        let decision = TwoPhaseDecision::Committed {
            commit_ts: 12345,
            participants: vec![0, 1],
        };
        let json = serde_json::to_string(&decision).unwrap();
        let back: TwoPhaseDecision = serde_json::from_str(&json).unwrap();
        match back {
            TwoPhaseDecision::Committed {
                commit_ts,
                participants,
            } => {
                assert_eq!(commit_ts, 12345);
                assert_eq!(participants, vec![0, 1]);
            },
            _ => panic!("Wrong variant"),
        }
    }
}
