//! Two-Phase Commit (2PC) for cross-partition writes.
//!
//! When a mutation writes to tables on multiple partitions, the
//! single-partition fast path (TiDB 1PC pattern) cannot be used. Instead, we
//! use Vitess's 2PC protocol:
//!
//! 1. Coordinator detects cross-partition writes
//! 2. Sends Prepare to each partition's Committer
//! 3. Each Committer validates OCC, stages writes, persists redo log
//! 4. Coordinator records commit/rollback decision in NATS KV
//! 5. Sends CommitPrepared/RollbackPrepared to participants
//!
//! References:
//!   - Vitess: https://vitess.io/docs/22.0/reference/features/distributed-transaction/
//!   - TiDB 1PC: https://pingcap.github.io/tidb-dev-guide/understand-tidb/1pc.html
//!   - CockroachDB: https://www.cockroachlabs.com/blog/parallel-commits/

use std::{
    collections::BTreeMap,
    sync::Arc,
    time::{
        Duration,
        SystemTime,
        UNIX_EPOCH,
    },
};

use anyhow::Context;
use async_nats::jetstream::kv::{
    Operation as KvOperation,
    Store,
};
use async_trait::async_trait;
use common::{
    bootstrap_model::index::database_index::IndexedFields,
    document::DocumentUpdateWithPrevTs,
    grpc::ClusterGrpcAuth,
    interval::IntervalSet,
    query::FilterValue,
    sha256::Sha256,
    types::{
        IndexDescriptor,
        RepeatableTimestamp,
        TabletIndexName,
        Timestamp,
    },
};
use pb::{
    common::RepeatableTimestamp as RepeatableTimestampProto,
    replication::{
        two_phase_commit_service_client::TwoPhaseCommitServiceClient as TonicTwoPcClient,
        TwoPcCommitRequest,
        TwoPcFilterConditionRead,
        TwoPcIndexedRead,
        TwoPcParticipantTransaction as TwoPcParticipantTransactionProto,
        TwoPcPrepareRequest,
        TwoPcPrepareResponse,
        TwoPcRollbackRequest,
        TwoPcSearchRead,
        TwoPcTabletMetadata,
        TwoPcTextQueryTermRead,
        TwoPcValidateReadsRequest,
    },
    searchlight,
};
use prost::Message;
use search::{
    query::{
        FuzzyDistance,
        QueryReads,
        TextQueryTerm,
    },
    FilterConditionRead,
    TextQueryTermRead,
};
use serde::{
    Deserialize,
    Serialize,
};
use tokio::sync::Mutex;
use tonic::{
    transport::{
        Channel,
        Endpoint,
    },
    Request,
};
use value::{
    FieldPath,
    TableName,
    TableNamespace,
    TableNumber,
    TabletId,
};

use crate::{
    partition::{
        routed_partition_for_table,
        PartitionId,
        PartitionMap,
    },
    reads::{
        IndexReads,
        ReadSet,
    },
    transaction::FinalTransaction,
    write_log::WriteSource,
};

const TWO_PHASE_GRPC_TIMEOUT: Duration = Duration::from_secs(10);

/// Globally unique transaction ID for 2PC.
/// Generated by the coordinator using UUID v4.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TwoPhaseTransactionId(pub String);

impl TwoPhaseTransactionId {
    pub fn new() -> Self {
        Self(uuid::Uuid::new_v4().to_string())
    }
}

impl std::fmt::Display for TwoPhaseTransactionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// State of a 2PC transaction stored in NATS KV.
/// This is the commit decision record — the point of no return.
/// Follows Vitess's Metadata Manager (MM) pattern.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TwoPhaseDecision {
    /// A true parallel-commit attempt whose final status can be recovered by
    /// checking that every listed participant intent was durably staged.
    ///
    /// This variant is intentionally metadata-only for now: the live commit
    /// path still uses the conservative Committed/RolledBack decisions until
    /// staged-write reads and transaction status recovery are implemented.
    Staging {
        commit_ts: u64,
        participants: Vec<u32>,
        participant_intents: Vec<TwoPhaseParticipantIntent>,
        transaction_digest: TwoPhaseTransactionDigest,
        #[serde(default)]
        staged_at_unix_millis: Option<u64>,
        #[serde(default)]
        resolved_participants: Vec<u32>,
    },
    /// All participants prepared successfully. Commit.
    Committed {
        commit_ts: u64,
        participants: Vec<u32>,
        #[serde(default)]
        resolved_participants: Vec<u32>,
    },
    /// A participant failed to prepare, or coordinator timed out. Rollback.
    RolledBack {
        reason: String,
        participants: Vec<u32>,
        #[serde(default)]
        resolved_participants: Vec<u32>,
    },
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TwoPhaseTransactionDigest(pub String);

impl TwoPhaseTransactionDigest {
    pub fn from_staging_record(
        participants: &[u32],
        intents: &[TwoPhaseParticipantIntent],
    ) -> Self {
        let mut canonical_participants = participants.to_vec();
        canonical_participants.sort_unstable();
        canonical_participants.dedup();
        let mut canonical_intents = intents.to_vec();
        canonical_intents.sort_by_key(|intent| intent.partition_id);
        let mut bytes = Vec::new();
        for participant in canonical_participants {
            bytes.extend_from_slice(&participant.to_be_bytes());
        }
        bytes.push(0xff);
        for intent in canonical_intents {
            bytes.extend_from_slice(&intent.partition_id.to_be_bytes());
            bytes.extend_from_slice(&intent.prepare_ts.to_be_bytes());
            bytes.extend_from_slice(intent.participant_transaction_digest.as_bytes());
        }
        Self(hex::encode(Sha256::hash(&bytes)))
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TwoPhaseParticipantIntent {
    pub partition_id: u32,
    pub prepare_ts: u64,
    pub participant_transaction_digest: String,
}

impl TwoPhaseParticipantIntent {
    pub fn from_redo_entry(entry: &TwoPhaseRedoEntry) -> Self {
        Self {
            partition_id: entry.partition_id,
            prepare_ts: entry.prepare_ts,
            participant_transaction_digest: entry.participant_transaction_digest(),
        }
    }
}

impl TwoPhaseDecision {
    pub fn staging(
        commit_ts: u64,
        participants: Vec<u32>,
        participant_intents: Vec<TwoPhaseParticipantIntent>,
    ) -> Self {
        let mut participants = participants;
        participants.extend(participant_intents.iter().map(|intent| intent.partition_id));
        participants.sort_unstable();
        participants.dedup();
        let mut participant_intents = participant_intents;
        participant_intents.sort_by_key(|intent| intent.partition_id);
        let transaction_digest =
            TwoPhaseTransactionDigest::from_staging_record(&participants, &participant_intents);
        Self::Staging {
            commit_ts,
            participants,
            participant_intents,
            transaction_digest,
            staged_at_unix_millis: Some(now_unix_millis()),
            resolved_participants: Vec::new(),
        }
    }

    pub fn committed(commit_ts: u64, participants: Vec<u32>) -> Self {
        Self::Committed {
            commit_ts,
            participants,
            resolved_participants: Vec::new(),
        }
    }

    pub fn rolled_back(reason: String, participants: Vec<u32>) -> Self {
        Self::RolledBack {
            reason,
            participants,
            resolved_participants: Vec::new(),
        }
    }

    pub fn participants(&self) -> &[u32] {
        match self {
            Self::Staging { participants, .. }
            | Self::Committed { participants, .. }
            | Self::RolledBack { participants, .. } => participants,
        }
    }

    pub fn resolved_participants(&self) -> &[u32] {
        match self {
            Self::Staging {
                resolved_participants,
                ..
            }
            | Self::Committed {
                resolved_participants,
                ..
            }
            | Self::RolledBack {
                resolved_participants,
                ..
            } => resolved_participants,
        }
    }

    pub fn is_staging(&self) -> bool {
        matches!(self, Self::Staging { .. })
    }

    pub fn participant_intents(&self) -> &[TwoPhaseParticipantIntent] {
        match self {
            Self::Staging {
                participant_intents,
                ..
            } => participant_intents,
            Self::Committed { .. } | Self::RolledBack { .. } => &[],
        }
    }

    pub fn transaction_digest(&self) -> Option<&TwoPhaseTransactionDigest> {
        match self {
            Self::Staging {
                transaction_digest, ..
            } => Some(transaction_digest),
            Self::Committed { .. } | Self::RolledBack { .. } => None,
        }
    }

    pub fn mark_participant_resolved(&mut self, participant: PartitionId) {
        let resolved = match self {
            Self::Staging {
                resolved_participants,
                ..
            }
            | Self::Committed {
                resolved_participants,
                ..
            }
            | Self::RolledBack {
                resolved_participants,
                ..
            } => resolved_participants,
        };
        if !resolved.contains(&participant.0) {
            resolved.push(participant.0);
            resolved.sort_unstable();
            resolved.dedup();
        }
    }

    pub fn committed_from_staging(&self) -> Option<Self> {
        match self {
            Self::Staging {
                commit_ts,
                participants,
                resolved_participants,
                ..
            } if self.all_participants_staged() => Some(Self::Committed {
                commit_ts: *commit_ts,
                participants: participants.clone(),
                resolved_participants: resolved_participants.clone(),
            }),
            _ => None,
        }
    }

    pub fn staged_age(&self) -> Option<Duration> {
        let Self::Staging {
            staged_at_unix_millis: Some(staged_at),
            ..
        } = self
        else {
            return None;
        };
        let now = now_unix_millis();
        Some(Duration::from_millis(now.saturating_sub(*staged_at)))
    }

    pub fn mark_participant_staged(
        &mut self,
        intent: TwoPhaseParticipantIntent,
    ) -> anyhow::Result<()> {
        let Self::Staging {
            participants,
            participant_intents,
            transaction_digest,
            ..
        } = self
        else {
            return Ok(());
        };
        if !participants.contains(&intent.partition_id) {
            participants.push(intent.partition_id);
            participants.sort_unstable();
            participants.dedup();
        }
        if let Some(existing) = participant_intents
            .iter_mut()
            .find(|existing| existing.partition_id == intent.partition_id)
        {
            anyhow::ensure!(
                *existing == intent,
                "2PC staging proof for participant {} conflicts with the existing staged intent",
                intent.partition_id,
            );
            return Ok(());
        } else {
            participant_intents.push(intent);
        }
        participant_intents.sort_by_key(|intent| intent.partition_id);
        *transaction_digest =
            TwoPhaseTransactionDigest::from_staging_record(participants, participant_intents);
        Ok(())
    }

    pub fn all_participants_staged(&self) -> bool {
        match self {
            Self::Staging {
                participants,
                participant_intents,
                ..
            } => participants.iter().all(|participant| {
                participant_intents
                    .iter()
                    .any(|intent| intent.partition_id == *participant)
            }),
            Self::Committed { .. } | Self::RolledBack { .. } => true,
        }
    }

    pub fn all_participants_resolved(&self) -> bool {
        self.participants()
            .iter()
            .all(|participant| self.resolved_participants().contains(participant))
    }

    pub fn staged_read_policy(&self) -> StagedTransactionReadPolicy {
        match self {
            Self::Staging { .. } if self.all_participants_staged() => {
                StagedTransactionReadPolicy::RecoverStatusBeforeRead
            },
            Self::Staging { .. } => StagedTransactionReadPolicy::HidePendingParticipantProofs,
            Self::Committed { .. } => StagedTransactionReadPolicy::VisibleCommittedDecision,
            Self::RolledBack { .. } => StagedTransactionReadPolicy::HiddenRolledBackDecision,
        }
    }

    pub fn staged_subscription_policy(&self) -> StagedTransactionSubscriptionPolicy {
        match self {
            Self::Staging { .. } => StagedTransactionSubscriptionPolicy::SuppressUntilFinalDecision,
            Self::Committed { .. } => StagedTransactionSubscriptionPolicy::EmitCommittedDelta,
            Self::RolledBack { .. } => StagedTransactionSubscriptionPolicy::SuppressRolledBack,
        }
    }

    pub fn requires_status_recovery_before_read(&self) -> bool {
        matches!(
            self.staged_read_policy(),
            StagedTransactionReadPolicy::RecoverStatusBeforeRead
        )
    }

    pub fn staged_writes_visible_to_readers(&self) -> bool {
        matches!(
            self.staged_read_policy(),
            StagedTransactionReadPolicy::VisibleCommittedDecision
        )
    }

    pub fn should_emit_subscription_invalidation(&self) -> bool {
        matches!(
            self.staged_subscription_policy(),
            StagedTransactionSubscriptionPolicy::EmitCommittedDelta
        )
    }
}

/// Read behavior for writes represented by a staged parallel-commit decision.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StagedTransactionReadPolicy {
    /// The transaction is not yet recoverably committed. Reads must not expose
    /// its writes or use them for timestamped snapshots.
    HidePendingParticipantProofs,
    /// Every participant has staged its intent, but the final decision has not
    /// been recovered yet. A read at/after the transaction timestamp must first
    /// drive transaction-status recovery instead of showing tentative writes.
    RecoverStatusBeforeRead,
    /// A final committed decision exists, so normal committed-delta visibility
    /// and OCC behavior may apply.
    VisibleCommittedDecision,
    /// A final rollback decision exists. The staged writes are never visible.
    HiddenRolledBackDecision,
}

/// Subscription invalidation behavior for staged parallel-commit decisions.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StagedTransactionSubscriptionPolicy {
    /// No user-visible invalidation may be emitted while the transaction can
    /// still resolve to rollback.
    SuppressUntilFinalDecision,
    /// Emit the same invalidation path as an ordinary committed write.
    EmitCommittedDelta,
    /// Rollback cleanup does not represent a visible document change.
    SuppressRolledBack,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum StagingRecoveryResult {
    Missing,
    Pending(TwoPhaseDecision),
    Committed(TwoPhaseDecision),
    AlreadyFinal(TwoPhaseDecision),
}

/// Result from a successful Prepare on a participant.
#[derive(Debug)]
pub struct PrepareResult {
    /// The timestamp assigned to this partition's portion of the transaction.
    pub prepare_ts: Timestamp,
}

/// Redo log entry persisted during Prepare for crash recovery.
/// If a node crashes after Prepare but before CommitPrepared/RollbackPrepared,
/// the transaction watcher reads the redo log and resolves the transaction
/// by checking the decision record in NATS KV.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TwoPhaseRedoEntry {
    pub transaction_id: String,
    pub prepare_ts: u64,
    pub partition_id: u32,
    #[serde(default)]
    pub participants: Vec<u32>,
    #[serde(default)]
    pub prepared_at_unix_millis: Option<u64>,
    pub write_source: Option<String>,
    pub participant_transaction_hex: String,
}

impl TwoPhaseRedoEntry {
    pub fn new(
        transaction_id: &TwoPhaseTransactionId,
        prepare_ts: Timestamp,
        partition_id: PartitionId,
        transaction: ParticipantTransaction,
        write_source: &WriteSource,
    ) -> anyhow::Result<Self> {
        Self::new_with_participants(
            transaction_id,
            prepare_ts,
            partition_id,
            &[partition_id],
            transaction,
            write_source,
        )
    }

    pub fn new_with_participants(
        transaction_id: &TwoPhaseTransactionId,
        prepare_ts: Timestamp,
        partition_id: PartitionId,
        participants: &[PartitionId],
        transaction: ParticipantTransaction,
        write_source: &WriteSource,
    ) -> anyhow::Result<Self> {
        let proto = TwoPcParticipantTransactionProto::try_from(transaction)?;
        let mut bytes = Vec::new();
        proto
            .encode(&mut bytes)
            .context("2PC: Failed to encode participant transaction redo")?;
        Ok(Self {
            transaction_id: transaction_id.0.clone(),
            prepare_ts: u64::from(prepare_ts),
            partition_id: partition_id.0,
            participants: participants.iter().map(|partition| partition.0).collect(),
            prepared_at_unix_millis: Some(now_unix_millis()),
            write_source: write_source.as_str().map(str::to_string),
            participant_transaction_hex: hex::encode(bytes),
        })
    }

    pub fn transaction_id(&self) -> TwoPhaseTransactionId {
        TwoPhaseTransactionId(self.transaction_id.clone())
    }

    pub fn prepare_ts(&self) -> anyhow::Result<Timestamp> {
        self.prepare_ts.try_into()
    }

    pub fn partition_id(&self) -> PartitionId {
        PartitionId(self.partition_id)
    }

    pub fn participants(&self) -> Vec<PartitionId> {
        if self.participants.is_empty() {
            vec![self.partition_id()]
        } else {
            self.participants.iter().copied().map(PartitionId).collect()
        }
    }

    pub fn prepare_age(&self) -> Option<Duration> {
        let prepared_at = self.prepared_at_unix_millis?;
        let now = now_unix_millis();
        Some(Duration::from_millis(now.saturating_sub(prepared_at)))
    }

    pub fn prepare_timed_out(&self, timeout: Duration) -> bool {
        self.prepare_age().is_some_and(|age| age >= timeout)
    }

    pub fn write_source(&self) -> WriteSource {
        WriteSource::from(self.write_source.clone())
    }

    pub fn participant_transaction(&self) -> anyhow::Result<ParticipantTransaction> {
        let bytes = hex::decode(&self.participant_transaction_hex)
            .context("2PC: Failed to decode participant transaction redo")?;
        let proto = TwoPcParticipantTransactionProto::decode(bytes.as_slice())
            .context("2PC: Failed to parse participant transaction redo")?;
        ParticipantTransaction::try_from(proto)
    }

    pub fn participant_transaction_digest(&self) -> String {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.partition_id.to_be_bytes());
        bytes.extend_from_slice(&self.prepare_ts.to_be_bytes());
        bytes.extend_from_slice(self.participant_transaction_hex.as_bytes());
        hex::encode(Sha256::hash(&bytes))
    }
}

fn now_unix_millis() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
        .try_into()
        .unwrap_or(u64::MAX)
}

#[cfg(any(test, feature = "testing"))]
pub mod testing {
    use std::sync::Arc;

    use parking_lot::Mutex;

    use super::*;

    #[derive(Clone, Default)]
    pub struct InMemoryTwoPhaseDecisionLog {
        decisions: Arc<Mutex<BTreeMap<String, TwoPhaseDecision>>>,
    }

    impl InMemoryTwoPhaseDecisionLog {
        pub fn new() -> Self {
            Self::default()
        }

        pub fn decisions(&self) -> BTreeMap<String, TwoPhaseDecision> {
            self.decisions.lock().clone()
        }
    }

    #[async_trait]
    impl TwoPhaseDecisionLog for InMemoryTwoPhaseDecisionLog {
        async fn write_decision_if_absent(
            &self,
            transaction_id: &TwoPhaseTransactionId,
            decision: &TwoPhaseDecision,
        ) -> anyhow::Result<bool> {
            let mut decisions = self.decisions.lock();
            if decisions.contains_key(&transaction_id.0) {
                Ok(false)
            } else {
                decisions.insert(transaction_id.0.clone(), decision.clone());
                Ok(true)
            }
        }

        async fn get_decision(
            &self,
            transaction_id: &TwoPhaseTransactionId,
        ) -> anyhow::Result<Option<TwoPhaseDecision>> {
            Ok(self.decisions.lock().get(&transaction_id.0).cloned())
        }

        async fn mark_participant_resolved(
            &self,
            transaction_id: &TwoPhaseTransactionId,
            participant: PartitionId,
        ) -> anyhow::Result<Option<TwoPhaseDecision>> {
            let mut decisions = self.decisions.lock();
            let Some(decision) = decisions.get_mut(&transaction_id.0) else {
                return Ok(None);
            };
            decision.mark_participant_resolved(participant);
            Ok(Some(decision.clone()))
        }

        async fn mark_participant_staged(
            &self,
            transaction_id: &TwoPhaseTransactionId,
            intent: TwoPhaseParticipantIntent,
        ) -> anyhow::Result<Option<TwoPhaseDecision>> {
            let mut decisions = self.decisions.lock();
            let Some(decision) = decisions.get_mut(&transaction_id.0) else {
                return Ok(None);
            };
            decision.mark_participant_staged(intent)?;
            Ok(Some(decision.clone()))
        }

        async fn recover_staging_decision(
            &self,
            transaction_id: &TwoPhaseTransactionId,
        ) -> anyhow::Result<StagingRecoveryResult> {
            let mut decisions = self.decisions.lock();
            let Some(decision) = decisions.get_mut(&transaction_id.0) else {
                return Ok(StagingRecoveryResult::Missing);
            };
            if !decision.is_staging() {
                return Ok(StagingRecoveryResult::AlreadyFinal(decision.clone()));
            }
            let Some(committed) = decision.committed_from_staging() else {
                return Ok(StagingRecoveryResult::Pending(decision.clone()));
            };
            *decision = committed.clone();
            Ok(StagingRecoveryResult::Committed(committed))
        }

        async fn delete_decision(
            &self,
            transaction_id: &TwoPhaseTransactionId,
        ) -> anyhow::Result<()> {
            self.decisions.lock().remove(&transaction_id.0);
            Ok(())
        }
    }
}

/// NATS KV key prefix for 2PC decision records.
pub const TWO_PHASE_KV_PREFIX: &str = "2pc_";

/// NATS KV bucket for 2PC state.
pub const TWO_PHASE_KV_BUCKET: &str = "convex_2pc";

/// Timeout for prepared transactions before the watcher rolls them back.
pub const PREPARE_TIMEOUT_SECS: u64 = 30;

pub fn two_phase_decision_key(transaction_id: &TwoPhaseTransactionId) -> String {
    format!("{TWO_PHASE_KV_PREFIX}{}", transaction_id.0)
}

#[async_trait]
pub trait TwoPhaseDecisionLog: Send + Sync + 'static {
    async fn write_decision_if_absent(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        decision: &TwoPhaseDecision,
    ) -> anyhow::Result<bool>;

    async fn get_decision(
        &self,
        _transaction_id: &TwoPhaseTransactionId,
    ) -> anyhow::Result<Option<TwoPhaseDecision>> {
        Ok(None)
    }

    async fn write_decision(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        decision: &TwoPhaseDecision,
    ) -> anyhow::Result<()> {
        if self
            .write_decision_if_absent(transaction_id, decision)
            .await?
        {
            return Ok(());
        }
        let existing = self.get_decision(transaction_id).await?.with_context(|| {
            format!("2PC: decision for {transaction_id} already existed but could not be read")
        })?;
        anyhow::ensure!(
            existing == *decision,
            "2PC: durable decision for {} is already {:?}, cannot overwrite with {:?}",
            transaction_id,
            existing,
            decision,
        );
        Ok(())
    }

    async fn mark_participant_resolved(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        participant: PartitionId,
    ) -> anyhow::Result<Option<TwoPhaseDecision>>;

    async fn mark_participant_staged(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        intent: TwoPhaseParticipantIntent,
    ) -> anyhow::Result<Option<TwoPhaseDecision>>;

    async fn recover_staging_decision(
        &self,
        transaction_id: &TwoPhaseTransactionId,
    ) -> anyhow::Result<StagingRecoveryResult>;

    async fn delete_decision(&self, transaction_id: &TwoPhaseTransactionId) -> anyhow::Result<()>;
}

pub struct NoopTwoPhaseDecisionLog;

#[async_trait]
impl TwoPhaseDecisionLog for NoopTwoPhaseDecisionLog {
    async fn write_decision_if_absent(
        &self,
        _transaction_id: &TwoPhaseTransactionId,
        _decision: &TwoPhaseDecision,
    ) -> anyhow::Result<bool> {
        Ok(true)
    }

    async fn mark_participant_resolved(
        &self,
        _transaction_id: &TwoPhaseTransactionId,
        _participant: PartitionId,
    ) -> anyhow::Result<Option<TwoPhaseDecision>> {
        Ok(None)
    }

    async fn mark_participant_staged(
        &self,
        _transaction_id: &TwoPhaseTransactionId,
        _intent: TwoPhaseParticipantIntent,
    ) -> anyhow::Result<Option<TwoPhaseDecision>> {
        Ok(None)
    }

    async fn recover_staging_decision(
        &self,
        _transaction_id: &TwoPhaseTransactionId,
    ) -> anyhow::Result<StagingRecoveryResult> {
        Ok(StagingRecoveryResult::Missing)
    }

    async fn delete_decision(&self, _transaction_id: &TwoPhaseTransactionId) -> anyhow::Result<()> {
        Ok(())
    }
}

#[derive(Clone)]
pub struct NatsTwoPhaseDecisionLog {
    kv: Store,
}

impl NatsTwoPhaseDecisionLog {
    pub async fn connect(nats_url: &str) -> anyhow::Result<Self> {
        let _ = rustls::crypto::ring::default_provider().install_default();
        let client = async_nats::connect(nats_url)
            .await
            .with_context(|| format!("2PC: Failed to connect to NATS at {nats_url}"))?;
        let jetstream = async_nats::jetstream::new(client);
        let kv = jetstream
            .create_key_value(async_nats::jetstream::kv::Config {
                bucket: TWO_PHASE_KV_BUCKET.to_string(),
                history: 1,
                ..Default::default()
            })
            .await
            .context("2PC: Failed to create decision KV bucket")?;
        Ok(Self { kv })
    }
}

fn parse_nats_decision_entry(
    transaction_id: &TwoPhaseTransactionId,
    operation: KvOperation,
    value: &[u8],
) -> anyhow::Result<Option<TwoPhaseDecision>> {
    if operation != KvOperation::Put || value.is_empty() {
        return Ok(None);
    }
    serde_json::from_slice(value)
        .with_context(|| format!("2PC: Failed to parse decision for {transaction_id}"))
        .map(Some)
}

#[async_trait]
impl TwoPhaseDecisionLog for NatsTwoPhaseDecisionLog {
    async fn write_decision_if_absent(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        decision: &TwoPhaseDecision,
    ) -> anyhow::Result<bool> {
        let payload = serde_json::to_vec(decision)
            .with_context(|| format!("2PC: Failed to serialize decision for {transaction_id}"))?;
        match self
            .kv
            .create(two_phase_decision_key(transaction_id), payload.into())
            .await
        {
            Ok(_) => Ok(true),
            Err(_) => Ok(false),
        }
    }

    async fn get_decision(
        &self,
        transaction_id: &TwoPhaseTransactionId,
    ) -> anyhow::Result<Option<TwoPhaseDecision>> {
        let Some(entry) = self
            .kv
            .entry(two_phase_decision_key(transaction_id))
            .await
            .with_context(|| format!("2PC: Failed to read decision for {transaction_id}"))?
        else {
            return Ok(None);
        };
        parse_nats_decision_entry(transaction_id, entry.operation, &entry.value)
    }

    async fn mark_participant_resolved(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        participant: PartitionId,
    ) -> anyhow::Result<Option<TwoPhaseDecision>> {
        let key = two_phase_decision_key(transaction_id);
        for _ in 0..10 {
            let Some(entry) =
                self.kv.entry(key.clone()).await.with_context(|| {
                    format!("2PC: Failed to read decision for {transaction_id}")
                })?
            else {
                return Ok(None);
            };
            let Some(mut decision) =
                parse_nats_decision_entry(transaction_id, entry.operation, &entry.value)?
            else {
                return Ok(None);
            };
            decision.mark_participant_resolved(participant);
            let payload = serde_json::to_vec(&decision).with_context(|| {
                format!("2PC: Failed to serialize decision for {transaction_id}")
            })?;
            match self
                .kv
                .update(key.clone(), payload.into(), entry.revision)
                .await
            {
                Ok(_) => return Ok(Some(decision)),
                Err(err)
                    if err.kind()
                        == async_nats::jetstream::kv::UpdateErrorKind::WrongLastRevision =>
                {
                    continue;
                },
                Err(err) => {
                    anyhow::bail!(
                        "2PC: Failed to mark {participant} resolved for {transaction_id}: {err:#}"
                    );
                },
            }
        }
        anyhow::bail!(
            "2PC: Failed to mark {participant} resolved for {transaction_id} after CAS retries"
        )
    }

    async fn mark_participant_staged(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        intent: TwoPhaseParticipantIntent,
    ) -> anyhow::Result<Option<TwoPhaseDecision>> {
        let key = two_phase_decision_key(transaction_id);
        for _ in 0..10 {
            let Some(entry) =
                self.kv.entry(key.clone()).await.with_context(|| {
                    format!("2PC: Failed to read decision for {transaction_id}")
                })?
            else {
                return Ok(None);
            };
            let Some(mut decision) =
                parse_nats_decision_entry(transaction_id, entry.operation, &entry.value)?
            else {
                return Ok(None);
            };
            decision.mark_participant_staged(intent.clone())?;
            let payload = serde_json::to_vec(&decision).with_context(|| {
                format!("2PC: Failed to serialize decision for {transaction_id}")
            })?;
            match self
                .kv
                .update(key.clone(), payload.into(), entry.revision)
                .await
            {
                Ok(_) => return Ok(Some(decision)),
                Err(err)
                    if err.kind()
                        == async_nats::jetstream::kv::UpdateErrorKind::WrongLastRevision =>
                {
                    continue;
                },
                Err(err) => {
                    anyhow::bail!(
                        "2PC: Failed to mark participant {} staged for {transaction_id}: {err:#}",
                        intent.partition_id,
                    );
                },
            }
        }
        anyhow::bail!(
            "2PC: Failed to mark participant {} staged for {transaction_id} after CAS retries",
            intent.partition_id,
        )
    }

    async fn recover_staging_decision(
        &self,
        transaction_id: &TwoPhaseTransactionId,
    ) -> anyhow::Result<StagingRecoveryResult> {
        let key = two_phase_decision_key(transaction_id);
        for _ in 0..10 {
            let Some(entry) =
                self.kv.entry(key.clone()).await.with_context(|| {
                    format!("2PC: Failed to read decision for {transaction_id}")
                })?
            else {
                return Ok(StagingRecoveryResult::Missing);
            };
            let Some(decision) =
                parse_nats_decision_entry(transaction_id, entry.operation, &entry.value)?
            else {
                return Ok(StagingRecoveryResult::Missing);
            };
            if !decision.is_staging() {
                return Ok(StagingRecoveryResult::AlreadyFinal(decision));
            }
            let Some(committed) = decision.committed_from_staging() else {
                return Ok(StagingRecoveryResult::Pending(decision));
            };
            let payload = serde_json::to_vec(&committed).with_context(|| {
                format!("2PC: Failed to serialize recovered decision for {transaction_id}")
            })?;
            match self
                .kv
                .update(key.clone(), payload.into(), entry.revision)
                .await
            {
                Ok(_) => return Ok(StagingRecoveryResult::Committed(committed)),
                Err(err)
                    if err.kind()
                        == async_nats::jetstream::kv::UpdateErrorKind::WrongLastRevision =>
                {
                    continue;
                },
                Err(err) => {
                    anyhow::bail!(
                        "2PC: Failed to recover staging decision for {transaction_id}: {err:#}"
                    );
                },
            }
        }
        anyhow::bail!(
            "2PC: Failed to recover staging decision for {transaction_id} after CAS retries"
        )
    }

    async fn delete_decision(&self, transaction_id: &TwoPhaseTransactionId) -> anyhow::Result<()> {
        self.kv
            .delete(two_phase_decision_key(transaction_id))
            .await
            .with_context(|| format!("2PC: Failed to delete decision for {transaction_id}"))?;
        Ok(())
    }
}

/// Partition-to-address mapping for gRPC communication.
/// Each entry maps a partition ID to one or more gRPC addresses for that
/// partition's Raft peers.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NodeAddresses {
    addresses: BTreeMap<PartitionId, Vec<String>>,
}

impl NodeAddresses {
    pub fn from_entries(addresses: BTreeMap<PartitionId, Vec<String>>) -> Self {
        Self {
            addresses: addresses
                .into_iter()
                .filter_map(|(partition, addresses)| {
                    let addresses = addresses
                        .into_iter()
                        .map(|address| address.trim().to_string())
                        .filter(|address| !address.is_empty())
                        .collect::<Vec<_>>();
                    (!addresses.is_empty()).then_some((partition, addresses))
                })
                .collect(),
        }
    }

    /// Parse from config string: "0=host:port|host:port,1=host:port|host:port".
    ///
    /// A partition can list multiple Raft peers with `|`, e.g.
    /// "0=node-p0a:50051|node-p0b:50051,1=node-p1a:50051|node-p1b:50051".
    pub fn from_config(config: &str) -> Self {
        let mut addresses = BTreeMap::new();
        if !config.is_empty() {
            for pair in config.split(',') {
                let pair = pair.trim();
                if let Some((id, addr)) = pair.split_once('=') {
                    if let Ok(partition_id) = id.trim().parse::<u32>() {
                        let peers = addr
                            .split('|')
                            .map(str::trim)
                            .filter(|addr| !addr.is_empty())
                            .map(str::to_string)
                            .collect();
                        addresses.insert(PartitionId(partition_id), peers);
                    }
                }
            }
        }
        Self::from_entries(addresses)
    }

    pub fn to_entries(&self) -> BTreeMap<PartitionId, Vec<String>> {
        self.addresses.clone()
    }

    /// Get the gRPC address for a partition.
    pub fn address_for(&self, partition: PartitionId) -> Option<&str> {
        self.addresses
            .get(&partition)
            .and_then(|addresses| addresses.first())
            .map(|s| s.as_str())
    }

    /// Get all configured gRPC addresses for a partition.
    pub fn addresses_for(&self, partition: PartitionId) -> Option<&[String]> {
        self.addresses.get(&partition).map(Vec::as_slice)
    }

    /// Get all known partitions.
    pub fn partitions(&self) -> Vec<PartitionId> {
        self.addresses.keys().copied().collect()
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ParticipantTabletMetadata {
    pub tablet_id: TabletId,
    pub namespace: TableNamespace,
    pub table_number: TableNumber,
    pub table_name: TableName,
}

#[derive(Clone, Debug)]
#[cfg_attr(any(test, feature = "testing"), derive(PartialEq))]
pub struct ParticipantTransaction {
    pub begin_timestamp: RepeatableTimestamp,
    pub tablet_metadata: BTreeMap<TabletId, ParticipantTabletMetadata>,
    pub reads: ReadSet,
    pub writes: Vec<DocumentUpdateWithPrevTs>,
}

impl ParticipantTransaction {
    pub fn from_final_transaction(
        transaction: &FinalTransaction,
        participant: PartitionId,
        write_indexes: &[usize],
        partition_map: &PartitionMap,
        write_source: &WriteSource,
    ) -> anyhow::Result<Self> {
        let selected_writes: Vec<_> = transaction
            .writes
            .coalesced_writes()
            .enumerate()
            .filter(|(index, _)| write_indexes.contains(index))
            .map(|(_, write)| write.clone())
            .collect();

        let belongs_to_participant = |tablet_id: TabletId| -> bool {
            let Ok(table_name) = transaction.table_mapping.tablet_name(tablet_id) else {
                return false;
            };
            match routed_partition_for_table(&table_name, partition_map, write_source) {
                Some(owner) => owner == participant,
                None => participant == partition_map.local_partition(),
            }
        };

        let indexed_reads = transaction
            .reads
            .read_set()
            .iter_indexed()
            .filter(|(index_name, _)| belongs_to_participant(*index_name.table()))
            .map(|(index_name, reads)| (index_name.clone(), reads.clone()))
            .collect();
        let search_reads = transaction
            .reads
            .read_set()
            .iter_search()
            .filter(|(index_name, _)| belongs_to_participant(*index_name.table()))
            .map(|(index_name, reads)| (index_name.clone(), reads.clone()))
            .collect();
        let reads = ReadSet::new(indexed_reads, search_reads);

        let mut tablet_metadata = BTreeMap::new();
        let mut record_tablet = |tablet_id: TabletId| -> anyhow::Result<()> {
            if tablet_metadata.contains_key(&tablet_id) {
                return Ok(());
            }
            let table_name = transaction.table_mapping.tablet_name(tablet_id)?;
            let table_number = transaction.table_mapping.tablet_number(tablet_id)?;
            let namespace = transaction.table_mapping.tablet_namespace(tablet_id)?;
            tablet_metadata.insert(
                tablet_id,
                ParticipantTabletMetadata {
                    tablet_id,
                    namespace,
                    table_number,
                    table_name,
                },
            );
            Ok(())
        };

        for (index_name, _) in reads.iter_indexed() {
            record_tablet(*index_name.table())?;
        }
        for (index_name, _) in reads.iter_search() {
            record_tablet(*index_name.table())?;
        }
        for write in &selected_writes {
            record_tablet(write.id.tablet_id)?;
        }

        Ok(Self {
            begin_timestamp: transaction.begin_timestamp,
            tablet_metadata,
            reads,
            writes: selected_writes,
        })
    }

    pub fn from_entire_final_transaction(transaction: &FinalTransaction) -> anyhow::Result<Self> {
        let selected_writes: Vec<_> = transaction.writes.coalesced_writes().cloned().collect();
        let mut tablet_metadata = BTreeMap::new();
        let mut record_tablet = |tablet_id: TabletId| -> anyhow::Result<()> {
            if tablet_metadata.contains_key(&tablet_id) {
                return Ok(());
            }
            let table_name = transaction.table_mapping.tablet_name(tablet_id)?;
            let table_number = transaction.table_mapping.tablet_number(tablet_id)?;
            let namespace = transaction.table_mapping.tablet_namespace(tablet_id)?;
            tablet_metadata.insert(
                tablet_id,
                ParticipantTabletMetadata {
                    tablet_id,
                    namespace,
                    table_number,
                    table_name,
                },
            );
            Ok(())
        };

        for (index_name, _) in transaction.reads.read_set().iter_indexed() {
            record_tablet(*index_name.table())?;
        }
        for (index_name, _) in transaction.reads.read_set().iter_search() {
            record_tablet(*index_name.table())?;
        }
        for write in &selected_writes {
            record_tablet(write.id.tablet_id)?;
        }

        Ok(Self {
            begin_timestamp: transaction.begin_timestamp,
            tablet_metadata,
            reads: transaction.reads.read_set().clone(),
            writes: selected_writes,
        })
    }

    pub fn augment_table_mapping(
        &self,
        table_mapping: &mut value::TableMapping,
    ) -> anyhow::Result<()> {
        for metadata in self.tablet_metadata.values() {
            if table_mapping.tablet_id_exists(metadata.tablet_id) {
                continue;
            }
            table_mapping.insert_tablet(
                metadata.tablet_id,
                metadata.namespace,
                metadata.table_number,
                metadata.table_name.clone(),
            );
        }
        Ok(())
    }
}

fn descriptor_to_index_name(
    tablet_id: TabletId,
    descriptor: String,
) -> anyhow::Result<TabletIndexName> {
    match descriptor.as_str() {
        "by_id" => Ok(TabletIndexName::by_id(tablet_id)),
        "by_creation_time" => Ok(TabletIndexName::by_creation_time(tablet_id)),
        _ => TabletIndexName::new(tablet_id, IndexDescriptor::new(descriptor)?),
    }
}

fn tablet_id_to_bytes(tablet_id: TabletId) -> Vec<u8> {
    tablet_id.0 .0.to_vec()
}

fn tablet_id_from_bytes(bytes: Vec<u8>) -> anyhow::Result<TabletId> {
    Ok(TabletId(bytes.try_into()?))
}

impl TryFrom<TwoPcParticipantTransactionProto> for ParticipantTransaction {
    type Error = anyhow::Error;

    fn try_from(value: TwoPcParticipantTransactionProto) -> anyhow::Result<Self> {
        let begin_timestamp = value
            .begin_timestamp
            .context("TwoPcParticipantTransaction missing begin_timestamp")?
            .try_into()?;

        let tablet_metadata = value
            .tablet_metadata
            .into_iter()
            .map(
                |TwoPcTabletMetadata {
                     tablet_id,
                     component_id,
                     table_number,
                     table_name,
                 }| {
                    let tablet_id = tablet_id_from_bytes(tablet_id)?;
                    let namespace = match component_id {
                        Some(component_id) => TableNamespace::ByComponent(component_id.parse()?),
                        None => TableNamespace::Global,
                    };
                    let table_number = table_number.try_into()?;
                    let table_name = table_name.parse::<TableName>()?;
                    Ok((
                        tablet_id,
                        ParticipantTabletMetadata {
                            tablet_id,
                            namespace,
                            table_number,
                            table_name,
                        },
                    ))
                },
            )
            .collect::<anyhow::Result<BTreeMap<_, _>>>()?;

        let indexed_reads = value
            .indexed_reads
            .into_iter()
            .map(
                |TwoPcIndexedRead {
                     tablet_id,
                     descriptor,
                     fields,
                     intervals,
                 }| {
                    let tablet_id = tablet_id_from_bytes(tablet_id)?;
                    let index_name = descriptor_to_index_name(tablet_id, descriptor)?;
                    let fields = fields
                        .into_iter()
                        .map(FieldPath::try_from)
                        .collect::<anyhow::Result<Vec<_>>>()?;
                    let intervals = IntervalSet::try_from(intervals)?;
                    Ok((
                        index_name,
                        IndexReads {
                            fields: IndexedFields::try_from(fields)?,
                            intervals,
                            stack_traces: None,
                        },
                    ))
                },
            )
            .collect::<anyhow::Result<BTreeMap<_, _>>>()?;

        let search_reads = value
            .search_reads
            .into_iter()
            .map(
                |TwoPcSearchRead {
                     tablet_id,
                     descriptor,
                     text_queries,
                     filter_conditions,
                 }| {
                    let tablet_id = tablet_id_from_bytes(tablet_id)?;
                    let index_name = descriptor_to_index_name(tablet_id, descriptor)?;
                    let text_queries = text_queries
                        .into_iter()
                        .map(
                            |TwoPcTextQueryTermRead { field_path, term }| -> anyhow::Result<_> {
                                let field_path = field_path
                                    .context("TwoPcTextQueryTermRead missing field_path")?
                                    .try_into()?;
                                let term = text_query_term_from_proto(
                                    term.context("TwoPcTextQueryTermRead missing term")?,
                                )?;
                                Ok(TextQueryTermRead::new(field_path, term))
                            },
                        )
                        .collect::<anyhow::Result<Vec<_>>>()?;
                    let filter_conditions = filter_conditions
                        .into_iter()
                        .map(
                            |TwoPcFilterConditionRead { field_path, value }| -> anyhow::Result<_> {
                                let field_path = field_path
                                    .context("TwoPcFilterConditionRead missing field_path")?
                                    .try_into()?;
                                Ok(FilterConditionRead::Must(
                                    field_path,
                                    FilterValue::from(value),
                                ))
                            },
                        )
                        .collect::<anyhow::Result<Vec<_>>>()?;
                    Ok((
                        index_name,
                        QueryReads::new(text_queries.into(), filter_conditions.into()),
                    ))
                },
            )
            .collect::<anyhow::Result<BTreeMap<_, _>>>()?;

        let writes = value
            .writes
            .into_iter()
            .map(DocumentUpdateWithPrevTs::try_from)
            .collect::<anyhow::Result<Vec<_>>>()?;

        Ok(Self {
            begin_timestamp,
            tablet_metadata,
            reads: ReadSet::new(indexed_reads, search_reads),
            writes,
        })
    }
}

impl TryFrom<ParticipantTransaction> for TwoPcParticipantTransactionProto {
    type Error = anyhow::Error;

    fn try_from(value: ParticipantTransaction) -> anyhow::Result<Self> {
        let indexed_reads = value
            .reads
            .iter_indexed()
            .map(|(index_name, reads)| TwoPcIndexedRead {
                tablet_id: tablet_id_to_bytes(*index_name.table()),
                descriptor: index_name.descriptor().to_string(),
                fields: Vec::<pb::common::FieldPath>::from(reads.fields.clone()),
                intervals: reads.intervals.clone().into(),
            })
            .collect();

        let search_reads = value
            .reads
            .iter_search()
            .map(|(index_name, reads)| -> anyhow::Result<TwoPcSearchRead> {
                Ok(TwoPcSearchRead {
                    tablet_id: tablet_id_to_bytes(*index_name.table()),
                    descriptor: index_name.descriptor().to_string(),
                    text_queries: reads
                        .text_queries
                        .iter()
                        .map(|read| {
                            Ok(TwoPcTextQueryTermRead {
                                field_path: Some(read.field_path.clone().into()),
                                term: Some(text_query_term_to_proto(read.term.clone())),
                            })
                        })
                        .collect::<anyhow::Result<Vec<_>>>()?,
                    filter_conditions: reads
                        .filter_conditions
                        .iter()
                        .map(|read| match read {
                            FilterConditionRead::Must(field_path, value) => {
                                Ok(TwoPcFilterConditionRead {
                                    field_path: Some(field_path.clone().into()),
                                    value: value.clone().into(),
                                })
                            },
                        })
                        .collect::<anyhow::Result<Vec<_>>>()?,
                })
            })
            .collect::<anyhow::Result<Vec<_>>>()?;

        let writes = value
            .writes
            .into_iter()
            .map(pb::common::DocumentUpdateWithPrevTs::try_from)
            .collect::<anyhow::Result<Vec<_>>>()?;

        Ok(TwoPcParticipantTransactionProto {
            begin_timestamp: Some(RepeatableTimestampProto::from(value.begin_timestamp)),
            tablet_metadata: value
                .tablet_metadata
                .into_values()
                .map(|metadata| TwoPcTabletMetadata {
                    tablet_id: tablet_id_to_bytes(metadata.tablet_id),
                    component_id: match metadata.namespace {
                        TableNamespace::Global => None,
                        TableNamespace::ByComponent(component_id) => Some(component_id.encode()),
                    },
                    table_number: u32::from(metadata.table_number),
                    table_name: metadata.table_name.to_string(),
                })
                .collect(),
            indexed_reads,
            search_reads,
            writes,
        })
    }
}

fn text_query_term_from_proto(value: searchlight::TextQueryTerm) -> anyhow::Result<TextQueryTerm> {
    match value.term_type {
        Some(searchlight::text_query_term::TermType::Exact(exact)) => {
            Ok(TextQueryTerm::Exact(exact.token))
        },
        Some(searchlight::text_query_term::TermType::Fuzzy(fuzzy)) => Ok(TextQueryTerm::Fuzzy {
            token: fuzzy.token,
            max_distance: FuzzyDistance::try_from(fuzzy.max_distance as u8)?,
            prefix: fuzzy.prefix,
        }),
        None => anyhow::bail!("TextQueryTerm missing term_type"),
    }
}

fn text_query_term_to_proto(value: TextQueryTerm) -> searchlight::TextQueryTerm {
    let term_type = match value {
        TextQueryTerm::Exact(token) => {
            searchlight::text_query_term::TermType::Exact(searchlight::ExactTextTerm { token })
        },
        TextQueryTerm::Fuzzy {
            token,
            max_distance,
            prefix,
        } => searchlight::text_query_term::TermType::Fuzzy(searchlight::FuzzyTextTerm {
            token,
            max_distance: u8::from(max_distance) as u32,
            prefix,
        }),
    };
    searchlight::TextQueryTerm {
        term_type: Some(term_type),
    }
}

/// gRPC client for reaching remote partitions' 2PC service.
pub struct TwoPhaseCommitGrpcClient {
    client: TonicTwoPcClient<Channel>,
    cluster_auth: Option<ClusterGrpcAuth>,
}

fn normalize_grpc_addr(addr: &str) -> String {
    if addr.contains("://") {
        addr.to_string()
    } else {
        format!("http://{addr}")
    }
}

#[derive(Clone)]
pub struct TwoPhaseCommitGrpcClientPool {
    cluster_auth: Option<ClusterGrpcAuth>,
    clients: Arc<Mutex<BTreeMap<String, Arc<TwoPhaseCommitGrpcClient>>>>,
}

impl TwoPhaseCommitGrpcClientPool {
    pub fn new(cluster_auth: Option<ClusterGrpcAuth>) -> Self {
        Self {
            cluster_auth,
            clients: Arc::new(Mutex::new(BTreeMap::new())),
        }
    }

    pub async fn client(&self, addr: &str) -> anyhow::Result<Arc<TwoPhaseCommitGrpcClient>> {
        let normalized_addr = normalize_grpc_addr(addr);
        if let Some(client) = self.clients.lock().await.get(&normalized_addr).cloned() {
            return Ok(client);
        }

        let client = Arc::new(
            TwoPhaseCommitGrpcClient::connect_inner(&normalized_addr, self.cluster_auth.clone())
                .await?,
        );
        let mut clients = self.clients.lock().await;
        Ok(clients
            .entry(normalized_addr)
            .or_insert_with(|| client.clone())
            .clone())
    }
}

impl TwoPhaseCommitGrpcClient {
    pub async fn connect(addr: &str) -> anyhow::Result<Self> {
        Self::connect_inner(addr, None).await
    }

    pub async fn connect_with_auth(
        addr: &str,
        cluster_auth: ClusterGrpcAuth,
    ) -> anyhow::Result<Self> {
        Self::connect_inner(addr, Some(cluster_auth)).await
    }

    async fn connect_inner(
        addr: &str,
        cluster_auth: Option<ClusterGrpcAuth>,
    ) -> anyhow::Result<Self> {
        let normalized_addr = normalize_grpc_addr(addr);
        let endpoint = Endpoint::from_shared(normalized_addr.clone())
            .with_context(|| format!("Invalid 2PC service address {normalized_addr}"))?
            .connect_timeout(TWO_PHASE_GRPC_TIMEOUT)
            .timeout(TWO_PHASE_GRPC_TIMEOUT);
        let channel = endpoint
            .connect()
            .await
            .with_context(|| format!("Failed to connect to 2PC service at {normalized_addr}"))?;
        let client = TonicTwoPcClient::new(channel);
        Ok(Self {
            client,
            cluster_auth,
        })
    }

    fn request<T>(&self, message: T) -> Request<T> {
        match &self.cluster_auth {
            Some(auth) => auth.request(message),
            None => Request::new(message),
        }
    }

    pub async fn prepare(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        transaction: ParticipantTransaction,
        write_source: WriteSource,
        prepare_ts: Timestamp,
        placement_version: crate::partition::PlacementVersion,
        participants: &[PartitionId],
    ) -> anyhow::Result<PrepareResult> {
        let request = TwoPcPrepareRequest {
            transaction_id: transaction_id.0.clone(),
            transaction: Some(transaction.try_into()?),
            write_source: write_source.as_str().unwrap_or_default().to_string(),
            prepare_ts: u64::from(prepare_ts),
            placement_version: u64::from(placement_version),
            participants: participants.iter().map(|partition| partition.0).collect(),
        };
        let response = self
            .client
            .clone()
            .prepare(self.request(request))
            .await
            .context("gRPC Prepare failed")?;
        let TwoPcPrepareResponse { prepare_ts } = response.into_inner();
        Ok(PrepareResult {
            prepare_ts: prepare_ts.try_into()?,
        })
    }

    pub async fn validate_reads(
        &self,
        transaction_id: &TwoPhaseTransactionId,
        transaction: ParticipantTransaction,
        write_source: WriteSource,
        validate_ts: Timestamp,
        placement_version: crate::partition::PlacementVersion,
    ) -> anyhow::Result<()> {
        let request = TwoPcValidateReadsRequest {
            transaction_id: transaction_id.0.clone(),
            transaction: Some(transaction.try_into()?),
            write_source: write_source.as_str().unwrap_or_default().to_string(),
            validate_ts: u64::from(validate_ts),
            placement_version: u64::from(placement_version),
        };
        self.client
            .clone()
            .validate_reads(self.request(request))
            .await
            .context("gRPC ValidateReads failed")?;
        Ok(())
    }

    pub async fn commit_prepared(
        &self,
        transaction_id: &TwoPhaseTransactionId,
    ) -> anyhow::Result<u64> {
        let request = TwoPcCommitRequest {
            transaction_id: transaction_id.0.clone(),
        };
        let response = self
            .client
            .clone()
            .commit_prepared(self.request(request))
            .await
            .context("gRPC CommitPrepared failed")?;
        Ok(response.into_inner().commit_ts)
    }

    pub async fn rollback_prepared(
        &self,
        transaction_id: &TwoPhaseTransactionId,
    ) -> anyhow::Result<()> {
        let request = TwoPcRollbackRequest {
            transaction_id: transaction_id.0.clone(),
        };
        self.client
            .clone()
            .rollback_prepared(self.request(request))
            .await
            .context("gRPC RollbackPrepared failed")?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_node_addresses_parsing() {
        let addrs = NodeAddresses::from_config("0=node-a:50051,1=node-b:50051");
        assert_eq!(addrs.address_for(PartitionId(0)), Some("node-a:50051"));
        assert_eq!(addrs.address_for(PartitionId(1)), Some("node-b:50051"));
        assert_eq!(
            addrs.addresses_for(PartitionId(0)).unwrap(),
            &["node-a:50051".to_string()]
        );
        assert_eq!(addrs.address_for(PartitionId(2)), None);
    }

    #[test]
    fn test_node_addresses_parsing_multiple_peers() {
        let addrs = NodeAddresses::from_config(
            "0=node-p0a:50051|node-p0b:50051|node-p0c:50051,1=node-p1a:50051",
        );
        assert_eq!(addrs.address_for(PartitionId(0)), Some("node-p0a:50051"));
        assert_eq!(
            addrs.addresses_for(PartitionId(0)).unwrap(),
            &[
                "node-p0a:50051".to_string(),
                "node-p0b:50051".to_string(),
                "node-p0c:50051".to_string(),
            ]
        );
        assert_eq!(
            addrs.addresses_for(PartitionId(1)).unwrap(),
            &["node-p1a:50051".to_string()]
        );
    }

    #[test]
    fn test_node_addresses_empty() {
        let addrs = NodeAddresses::from_config("");
        assert!(addrs.partitions().is_empty());
    }

    #[test]
    fn test_node_addresses_round_trip_structured_entries() {
        let addrs = NodeAddresses::from_entries(BTreeMap::from([
            (
                PartitionId(0),
                vec![" node-p0a:50051 ".to_string(), "node-p0b:50051".to_string()],
            ),
            (
                PartitionId(1),
                vec!["".to_string(), "node-p1a:50051".to_string()],
            ),
            (PartitionId(2), vec!["".to_string()]),
        ]));

        assert_eq!(addrs.address_for(PartitionId(0)), Some("node-p0a:50051"));
        assert_eq!(addrs.address_for(PartitionId(1)), Some("node-p1a:50051"));
        assert_eq!(addrs.address_for(PartitionId(2)), None);
        assert_eq!(NodeAddresses::from_entries(addrs.to_entries()), addrs);
    }

    #[test]
    fn test_two_phase_transaction_id() {
        let id1 = TwoPhaseTransactionId::new();
        let id2 = TwoPhaseTransactionId::new();
        assert_ne!(id1, id2);
    }

    #[test]
    fn test_decision_serialization() {
        let mut decision = TwoPhaseDecision::committed(12345, vec![0, 1]);
        decision.mark_participant_resolved(PartitionId(0));
        let json = serde_json::to_string(&decision).unwrap();
        let back: TwoPhaseDecision = serde_json::from_str(&json).unwrap();
        match back {
            TwoPhaseDecision::Committed {
                commit_ts,
                participants,
                resolved_participants,
            } => {
                assert_eq!(commit_ts, 12345);
                assert_eq!(participants, vec![0, 1]);
                assert_eq!(resolved_participants, vec![0]);
            },
            _ => panic!("Wrong variant"),
        }
    }

    fn participant_intent(
        partition_id: u32,
        prepare_ts: u64,
        digest: &str,
    ) -> TwoPhaseParticipantIntent {
        TwoPhaseParticipantIntent {
            partition_id,
            prepare_ts,
            participant_transaction_digest: digest.to_string(),
        }
    }

    #[test]
    fn test_staging_decision_serialization() {
        let decision = TwoPhaseDecision::staging(
            12345,
            vec![1, 0],
            vec![
                participant_intent(1, 12345, "participant-one"),
                participant_intent(0, 12345, "participant-zero"),
            ],
        );
        let json = serde_json::to_string(&decision).unwrap();
        let back: TwoPhaseDecision = serde_json::from_str(&json).unwrap();
        match back {
            TwoPhaseDecision::Staging {
                commit_ts,
                participants,
                participant_intents,
                transaction_digest,
                staged_at_unix_millis,
                resolved_participants,
            } => {
                assert_eq!(commit_ts, 12345);
                assert_eq!(participants, vec![0, 1]);
                assert_eq!(
                    participant_intents,
                    vec![
                        participant_intent(0, 12345, "participant-zero"),
                        participant_intent(1, 12345, "participant-one"),
                    ]
                );
                assert_eq!(Some(&transaction_digest), decision.transaction_digest(),);
                assert!(staged_at_unix_millis.is_some());
                assert!(resolved_participants.is_empty());
            },
            _ => panic!("Wrong variant"),
        }
    }

    #[test]
    fn test_staging_digest_is_order_independent() {
        let first = TwoPhaseDecision::staging(
            12345,
            vec![0, 1],
            vec![
                participant_intent(0, 12345, "participant-zero"),
                participant_intent(1, 12345, "participant-one"),
            ],
        );
        let second = TwoPhaseDecision::staging(
            12345,
            vec![1, 0],
            vec![
                participant_intent(1, 12345, "participant-one"),
                participant_intent(0, 12345, "participant-zero"),
            ],
        );
        assert_eq!(first.transaction_digest(), second.transaction_digest());
    }

    #[test]
    fn test_staging_tracks_missing_participant_intents() {
        let mut decision = TwoPhaseDecision::staging(
            12345,
            vec![0, 1],
            vec![participant_intent(0, 12345, "participant-zero")],
        );
        assert!(decision.is_staging());
        assert_eq!(decision.participants(), &[0, 1]);
        assert!(!decision.all_participants_staged());

        let digest_before = decision.transaction_digest().cloned();
        decision
            .mark_participant_staged(participant_intent(1, 12345, "participant-one"))
            .unwrap();
        assert!(decision.all_participants_staged());
        assert_ne!(digest_before.as_ref(), decision.transaction_digest());
        assert_eq!(
            decision.participant_intents(),
            &[
                participant_intent(0, 12345, "participant-zero"),
                participant_intent(1, 12345, "participant-one"),
            ],
        );
    }

    #[test]
    fn test_staging_mark_participant_staged_is_idempotent() {
        let mut decision = TwoPhaseDecision::staging(12345, vec![0], vec![]);
        let intent = participant_intent(0, 12345, "participant-zero");
        decision.mark_participant_staged(intent.clone()).unwrap();
        let digest_after_first = decision.transaction_digest().cloned();
        decision.mark_participant_staged(intent).unwrap();
        assert_eq!(decision.transaction_digest(), digest_after_first.as_ref());
        assert_eq!(decision.participant_intents().len(), 1);
    }

    #[test]
    fn test_staging_rejects_conflicting_duplicate_participant_intent() {
        let mut decision = TwoPhaseDecision::staging(
            12345,
            vec![0],
            vec![participant_intent(0, 12345, "participant-zero")],
        );
        let digest_before = decision.transaction_digest().cloned();
        let err = decision
            .mark_participant_staged(participant_intent(0, 12345, "different-transaction"))
            .expect_err("conflicting duplicate stage proof should fail closed");

        assert!(
            format!("{err:#}").contains("conflicts with the existing staged intent"),
            "unexpected error: {err:#}",
        );
        assert_eq!(decision.transaction_digest(), digest_before.as_ref());
        assert_eq!(
            decision.participant_intents(),
            &[participant_intent(0, 12345, "participant-zero")],
        );
    }

    #[test]
    fn test_staging_decision_is_not_cleanup_resolved_by_stage_proof() {
        let mut decision = TwoPhaseDecision::staging(
            12345,
            vec![0, 1],
            vec![
                participant_intent(0, 12345, "participant-zero"),
                participant_intent(1, 12345, "participant-one"),
            ],
        );
        assert!(decision.all_participants_staged());
        assert!(!decision.all_participants_resolved());

        decision.mark_participant_resolved(PartitionId(0));
        assert!(!decision.all_participants_resolved());
        decision.mark_participant_resolved(PartitionId(1));
        assert!(decision.all_participants_resolved());
    }

    #[test]
    fn test_incomplete_staging_is_hidden_from_reads_and_subscriptions() {
        let decision = TwoPhaseDecision::staging(
            12345,
            vec![0, 1],
            vec![participant_intent(0, 12345, "participant-zero")],
        );

        assert_eq!(
            decision.staged_read_policy(),
            StagedTransactionReadPolicy::HidePendingParticipantProofs,
        );
        assert_eq!(
            decision.staged_subscription_policy(),
            StagedTransactionSubscriptionPolicy::SuppressUntilFinalDecision,
        );
        assert!(!decision.requires_status_recovery_before_read());
        assert!(!decision.staged_writes_visible_to_readers());
        assert!(!decision.should_emit_subscription_invalidation());
    }

    #[test]
    fn test_complete_staging_requires_recovery_before_read() {
        let decision = TwoPhaseDecision::staging(
            12345,
            vec![0, 1],
            vec![
                participant_intent(0, 12345, "participant-zero"),
                participant_intent(1, 12345, "participant-one"),
            ],
        );

        assert_eq!(
            decision.staged_read_policy(),
            StagedTransactionReadPolicy::RecoverStatusBeforeRead,
        );
        assert_eq!(
            decision.staged_subscription_policy(),
            StagedTransactionSubscriptionPolicy::SuppressUntilFinalDecision,
        );
        assert!(decision.requires_status_recovery_before_read());
        assert!(!decision.staged_writes_visible_to_readers());
        assert!(!decision.should_emit_subscription_invalidation());
    }

    #[test]
    fn test_committed_decision_is_visible_and_invalidates_subscriptions() {
        let decision = TwoPhaseDecision::committed(12345, vec![0, 1]);

        assert_eq!(
            decision.staged_read_policy(),
            StagedTransactionReadPolicy::VisibleCommittedDecision,
        );
        assert_eq!(
            decision.staged_subscription_policy(),
            StagedTransactionSubscriptionPolicy::EmitCommittedDelta,
        );
        assert!(!decision.requires_status_recovery_before_read());
        assert!(decision.staged_writes_visible_to_readers());
        assert!(decision.should_emit_subscription_invalidation());
    }

    #[test]
    fn test_rolled_back_decision_is_hidden_and_does_not_invalidate_subscriptions() {
        let decision = TwoPhaseDecision::rolled_back("prepare failed".to_string(), vec![0, 1]);

        assert_eq!(
            decision.staged_read_policy(),
            StagedTransactionReadPolicy::HiddenRolledBackDecision,
        );
        assert_eq!(
            decision.staged_subscription_policy(),
            StagedTransactionSubscriptionPolicy::SuppressRolledBack,
        );
        assert!(!decision.requires_status_recovery_before_read());
        assert!(!decision.staged_writes_visible_to_readers());
        assert!(!decision.should_emit_subscription_invalidation());
    }

    #[test]
    fn test_nats_decision_entry_delete_marker_is_absent() {
        let txn_id = TwoPhaseTransactionId::new();
        let parsed = parse_nats_decision_entry(&txn_id, KvOperation::Delete, &[]).unwrap();
        assert_eq!(parsed, None);
    }

    #[test]
    fn test_nats_decision_entry_empty_put_is_absent() {
        let txn_id = TwoPhaseTransactionId::new();
        let parsed = parse_nats_decision_entry(&txn_id, KvOperation::Put, &[]).unwrap();
        assert_eq!(parsed, None);
    }

    #[test]
    fn test_nats_decision_entry_put_parses_decision() {
        let txn_id = TwoPhaseTransactionId::new();
        let decision = TwoPhaseDecision::committed(12345, vec![0, 1]);
        let payload = serde_json::to_vec(&decision).unwrap();
        let parsed = parse_nats_decision_entry(&txn_id, KvOperation::Put, &payload)
            .unwrap()
            .unwrap();
        assert_eq!(parsed, decision);
    }

    #[test]
    fn test_in_memory_decision_log_write_staging_if_absent_is_idempotent() {
        futures::executor::block_on(async {
            let log = testing::InMemoryTwoPhaseDecisionLog::new();
            let txn_id = TwoPhaseTransactionId("staging-idempotent".to_string());
            let staging = TwoPhaseDecision::staging(
                12345,
                vec![0, 1],
                vec![participant_intent(0, 12345, "participant-zero")],
            );
            let committed = TwoPhaseDecision::committed(12345, vec![0, 1]);

            assert!(log
                .write_decision_if_absent(&txn_id, &staging)
                .await
                .unwrap());
            assert!(!log
                .write_decision_if_absent(&txn_id, &committed)
                .await
                .unwrap());
            assert_eq!(log.get_decision(&txn_id).await.unwrap(), Some(staging));
        });
    }

    #[test]
    fn test_decision_log_write_decision_is_idempotent_for_same_decision() {
        futures::executor::block_on(async {
            let log = testing::InMemoryTwoPhaseDecisionLog::new();
            let txn_id = TwoPhaseTransactionId("same-decision-idempotent".to_string());
            let decision = TwoPhaseDecision::committed(12345, vec![0, 1]);

            log.write_decision(&txn_id, &decision).await.unwrap();
            log.write_decision(&txn_id, &decision).await.unwrap();

            assert_eq!(log.get_decision(&txn_id).await.unwrap(), Some(decision));
        });
    }

    #[test]
    fn test_decision_log_write_decision_rejects_conflicting_existing_decision() {
        futures::executor::block_on(async {
            let log = testing::InMemoryTwoPhaseDecisionLog::new();
            let txn_id = TwoPhaseTransactionId("commit-after-timeout-rollback".to_string());
            let rollback =
                TwoPhaseDecision::rolled_back("prepare timed out".to_string(), vec![0, 1]);
            let committed = TwoPhaseDecision::committed(12345, vec![0, 1]);

            log.write_decision(&txn_id, &rollback).await.unwrap();
            let err = log
                .write_decision(&txn_id, &committed)
                .await
                .expect_err("a final commit must not overwrite an existing rollback");
            assert!(
                format!("{err:#}").contains("cannot overwrite"),
                "unexpected error: {err:#}",
            );
            assert_eq!(log.get_decision(&txn_id).await.unwrap(), Some(rollback));
        });
    }

    #[test]
    fn test_in_memory_decision_log_marks_participant_staged() {
        futures::executor::block_on(async {
            let log = testing::InMemoryTwoPhaseDecisionLog::new();
            let txn_id = TwoPhaseTransactionId("staging-progress".to_string());
            let staging = TwoPhaseDecision::staging(
                12345,
                vec![0, 1],
                vec![participant_intent(0, 12345, "participant-zero")],
            );
            log.write_decision(&txn_id, &staging).await.unwrap();

            let updated = log
                .mark_participant_staged(&txn_id, participant_intent(1, 12345, "participant-one"))
                .await
                .unwrap()
                .unwrap();
            assert!(updated.all_participants_staged());
            assert_eq!(
                updated.participant_intents(),
                &[
                    participant_intent(0, 12345, "participant-zero"),
                    participant_intent(1, 12345, "participant-one"),
                ],
            );
        });
    }

    #[test]
    fn test_in_memory_decision_log_rejects_conflicting_duplicate_stage_proof() {
        futures::executor::block_on(async {
            let log = testing::InMemoryTwoPhaseDecisionLog::new();
            let txn_id = TwoPhaseTransactionId("staging-conflict".to_string());
            let staging = TwoPhaseDecision::staging(
                12345,
                vec![0],
                vec![participant_intent(0, 12345, "participant-zero")],
            );
            log.write_decision(&txn_id, &staging).await.unwrap();

            let err = log
                .mark_participant_staged(
                    &txn_id,
                    participant_intent(0, 12345, "different-transaction"),
                )
                .await
                .expect_err("conflicting duplicate stage proof should fail closed");
            assert!(
                format!("{err:#}").contains("conflicts with the existing staged intent"),
                "unexpected error: {err:#}",
            );
            assert_eq!(log.get_decision(&txn_id).await.unwrap(), Some(staging));
        });
    }

    #[test]
    fn test_in_memory_decision_log_recovers_complete_staging_to_committed() {
        futures::executor::block_on(async {
            let log = testing::InMemoryTwoPhaseDecisionLog::new();
            let txn_id = TwoPhaseTransactionId("staging-recovery".to_string());
            let staging = TwoPhaseDecision::staging(
                12345,
                vec![0, 1],
                vec![
                    participant_intent(0, 12345, "participant-zero"),
                    participant_intent(1, 12345, "participant-one"),
                ],
            );
            log.write_decision(&txn_id, &staging).await.unwrap();

            let result = log.recover_staging_decision(&txn_id).await.unwrap();
            let StagingRecoveryResult::Committed(TwoPhaseDecision::Committed {
                commit_ts,
                participants,
                resolved_participants,
            }) = result
            else {
                panic!("expected committed recovery");
            };
            assert_eq!(commit_ts, 12345);
            assert_eq!(participants, vec![0, 1]);
            assert!(resolved_participants.is_empty());
            assert_eq!(
                log.get_decision(&txn_id).await.unwrap(),
                Some(TwoPhaseDecision::committed(12345, vec![0, 1])),
            );
        });
    }

    #[test]
    fn test_in_memory_decision_log_leaves_incomplete_staging_pending() {
        futures::executor::block_on(async {
            let log = testing::InMemoryTwoPhaseDecisionLog::new();
            let txn_id = TwoPhaseTransactionId("staging-pending".to_string());
            let staging = TwoPhaseDecision::staging(
                12345,
                vec![0, 1],
                vec![participant_intent(0, 12345, "participant-zero")],
            );
            log.write_decision(&txn_id, &staging).await.unwrap();

            let result = log.recover_staging_decision(&txn_id).await.unwrap();
            assert_eq!(result, StagingRecoveryResult::Pending(staging.clone()));
            assert_eq!(log.get_decision(&txn_id).await.unwrap(), Some(staging));
        });
    }

    #[test]
    fn test_in_memory_decision_log_recovery_is_idempotent_after_final_decision() {
        futures::executor::block_on(async {
            let log = testing::InMemoryTwoPhaseDecisionLog::new();
            let txn_id = TwoPhaseTransactionId("staging-idempotent-recovery".to_string());
            let staging = TwoPhaseDecision::staging(
                12345,
                vec![0],
                vec![participant_intent(0, 12345, "participant-zero")],
            );
            log.write_decision(&txn_id, &staging).await.unwrap();
            assert!(matches!(
                log.recover_staging_decision(&txn_id).await.unwrap(),
                StagingRecoveryResult::Committed(_),
            ));

            let result = log.recover_staging_decision(&txn_id).await.unwrap();
            assert_eq!(
                result,
                StagingRecoveryResult::AlreadyFinal(TwoPhaseDecision::committed(12345, vec![0])),
            );
        });
    }

    #[test]
    fn test_final_decision_survives_duplicate_and_complete_cleanup_marks() {
        futures::executor::block_on(async {
            let log = testing::InMemoryTwoPhaseDecisionLog::new();
            let txn_id = TwoPhaseTransactionId("post-ack-cleanup-recovery".to_string());
            let committed = TwoPhaseDecision::committed(12345, vec![0, 1]);
            log.write_decision(&txn_id, &committed).await.unwrap();

            let partially_resolved = log
                .mark_participant_resolved(&txn_id, PartitionId(0))
                .await
                .unwrap()
                .expect("commit decision should remain after first cleanup mark");
            assert_eq!(partially_resolved.resolved_participants(), &[0]);
            assert!(!partially_resolved.all_participants_resolved());

            let duplicate_resolution = log
                .mark_participant_resolved(&txn_id, PartitionId(0))
                .await
                .unwrap()
                .expect("duplicate cleanup mark must not delete the decision");
            assert_eq!(duplicate_resolution.resolved_participants(), &[0]);

            let fully_resolved = log
                .mark_participant_resolved(&txn_id, PartitionId(1))
                .await
                .unwrap()
                .expect("final cleanup mark must retain the decision for crash recovery");
            assert_eq!(fully_resolved.resolved_participants(), &[0, 1]);
            assert!(fully_resolved.all_participants_resolved());

            assert_eq!(
                log.recover_staging_decision(&txn_id).await.unwrap(),
                StagingRecoveryResult::AlreadyFinal(fully_resolved),
            );
        });
    }
}
