//! Two-Phase Commit (2PC) for cross-partition writes.
//!
//! When a mutation writes to tables on multiple partitions, the
//! single-partition fast path (TiDB 1PC pattern) cannot be used. Instead, we
//! use Vitess's 2PC protocol:
//!
//! 1. Coordinator detects cross-partition writes
//! 2. Sends Prepare to each partition's Committer
//! 3. Each Committer validates OCC, stages writes, persists redo log
//! 4. Coordinator records commit/rollback decision in NATS KV
//! 5. Sends CommitPrepared/RollbackPrepared to participants
//!
//! References:
//!   - Vitess: https://vitess.io/docs/22.0/reference/features/distributed-transaction/
//!   - TiDB 1PC: https://pingcap.github.io/tidb-dev-guide/understand-tidb/1pc.html
//!   - CockroachDB: https://www.cockroachlabs.com/blog/parallel-commits/

use std::collections::BTreeMap;

use common::{
    persistence::{
        DocumentLogEntry,
        PersistenceIndexEntry,
    },
    types::Timestamp,
};
use serde::{
    Deserialize,
    Serialize,
};

use crate::partition::PartitionId;

/// Globally unique transaction ID for 2PC.
/// Generated by the coordinator using UUID v4.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TwoPhaseTransactionId(pub String);

impl TwoPhaseTransactionId {
    pub fn new() -> Self {
        Self(uuid::Uuid::new_v4().to_string())
    }
}

impl std::fmt::Display for TwoPhaseTransactionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// State of a 2PC transaction stored in NATS KV.
/// This is the commit decision record — the point of no return.
/// Follows Vitess's Metadata Manager (MM) pattern.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum TwoPhaseDecision {
    /// All participants prepared successfully. Commit.
    Committed {
        commit_ts: u64,
        participants: Vec<u32>,
    },
    /// A participant failed to prepare, or coordinator timed out. Rollback.
    RolledBack {
        reason: String,
        participants: Vec<u32>,
    },
}

/// Result from a successful Prepare on a participant.
#[derive(Debug)]
pub struct PrepareResult {
    /// The timestamp assigned to this partition's portion of the transaction.
    pub prepare_ts: Timestamp,
}

/// Redo log entry persisted during Prepare for crash recovery.
/// If a node crashes after Prepare but before CommitPrepared/RollbackPrepared,
/// the transaction watcher reads the redo log and resolves the transaction
/// by checking the decision record in NATS KV.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TwoPhaseRedoEntry {
    pub transaction_id: String,
    pub prepare_ts: u64,
    pub partition_id: u32,
    pub num_document_writes: usize,
    pub num_index_writes: usize,
}

/// NATS KV key prefix for 2PC decision records.
pub const TWO_PHASE_KV_PREFIX: &str = "2pc_";

/// NATS KV bucket for 2PC state.
pub const TWO_PHASE_KV_BUCKET: &str = "convex_2pc";

/// Timeout for prepared transactions before the watcher rolls them back.
pub const PREPARE_TIMEOUT_SECS: u64 = 30;

/// Partition-to-address mapping for gRPC communication.
/// Each entry maps a partition ID to the gRPC address of its owner node.
#[derive(Clone, Debug)]
pub struct NodeAddresses {
    addresses: BTreeMap<PartitionId, String>,
}

impl NodeAddresses {
    /// Parse from config string: "0=host:port,1=host:port"
    pub fn from_config(config: &str) -> Self {
        let mut addresses = BTreeMap::new();
        if !config.is_empty() {
            for pair in config.split(',') {
                let pair = pair.trim();
                if let Some((id, addr)) = pair.split_once('=') {
                    if let Ok(partition_id) = id.trim().parse::<u32>() {
                        addresses.insert(PartitionId(partition_id), addr.trim().to_string());
                    }
                }
            }
        }
        Self { addresses }
    }

    /// Get the gRPC address for a partition.
    pub fn address_for(&self, partition: PartitionId) -> Option<&str> {
        self.addresses.get(&partition).map(|s| s.as_str())
    }

    /// Get all known partitions.
    pub fn partitions(&self) -> Vec<PartitionId> {
        self.addresses.keys().copied().collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_node_addresses_parsing() {
        let addrs = NodeAddresses::from_config("0=node-a:50051,1=node-b:50051");
        assert_eq!(addrs.address_for(PartitionId(0)), Some("node-a:50051"));
        assert_eq!(addrs.address_for(PartitionId(1)), Some("node-b:50051"));
        assert_eq!(addrs.address_for(PartitionId(2)), None);
    }

    #[test]
    fn test_node_addresses_empty() {
        let addrs = NodeAddresses::from_config("");
        assert!(addrs.partitions().is_empty());
    }

    #[test]
    fn test_two_phase_transaction_id() {
        let id1 = TwoPhaseTransactionId::new();
        let id2 = TwoPhaseTransactionId::new();
        assert_ne!(id1, id2);
    }

    #[test]
    fn test_decision_serialization() {
        let decision = TwoPhaseDecision::Committed {
            commit_ts: 12345,
            participants: vec![0, 1],
        };
        let json = serde_json::to_string(&decision).unwrap();
        let back: TwoPhaseDecision = serde_json::from_str(&json).unwrap();
        match back {
            TwoPhaseDecision::Committed {
                commit_ts,
                participants,
            } => {
                assert_eq!(commit_ts, 12345);
                assert_eq!(participants, vec![0, 1]);
            },
            _ => panic!("Wrong variant"),
        }
    }
}
